Map<String, List<String>> freguesias = {
  'Águeda': [
    'Aguada de Cima',
    'Águeda e Borralha',
    'Barrô e Aguada de Baixo',
    'Belazaima do Chão, Castanheira do Vouga e Agadão',
    'Fermentelos',
    'Macinhata do Vouga',
    'Préstimo e Macieira de Alcoba',
    'Recardães e Espinhel',
    'Travassô e Óis da Ribeira',
    'Trofa, Segadães e Lamas do Vouga',
    'Valongo do Vouga'
  ],
  'Albergaria-a-Velha': [
    'Albergaria-a-Velha e Valmaior',
    'Alquerubim',
    'Angeja',
    'Branca',
    'Ribeira de Fráguas',
    'São João de Loure e Frossos'
  ],
  'Anadia': [
    'Amoreira da Gândara, Paredes do Bairro e Ancas',
    'Arcos e Mogofores',
    'Avelãs de Caminho',
    'Avelãs de Cima',
    'Moita',
    'Sangalhos',
    'São Lourenço do Bairro',
    'Tamengos, Aguim e Óis do Bairro',
    'Vila Nova de Monsarros',
    'Vilarinho do Bairro'
  ],
  'Arouca': [
    'Alvarenga',
    'Arouca e Burgo',
    'Cabreiros e Albergaria da Serra',
    'Canelas e Espiunca',
    'Chave',
    'Covelo de Paivó e Janarde',
    'Escariz',
    'Fermedo',
    'Mansores',
    'Moldes',
    'Rossas',
    'Santa Eulália',
    'São Miguel do Mato',
    'Tropeço',
    'Urrô',
    'Várzea'
  ],
  'Aveiro': [
    'Aradas',
    'Cacia',
    'Eirol e Eixo',
    'Esgueira',
    'Oliveirinha',
    'Requeixo, Nossa Senhora de Fátima e Nariz',
    'São Bernardo',
    'São Jacinto',
    'Vera Cruz e Glória',
    'Santa Joana (Aveiro)'
  ],
  'Castelo de Paiva': [
    'Fornos',
    'Raiva, Pedorido e Paraíso',
    'Real',
    'Santa Maria de Sardoura',
    'São Martinho de Sardoura',
    'Sobrado e Bairros'
  ],
  'Espinho': ['Anta e Guetim', 'Espinho', 'Paramos', 'Silvalde'],
  'Estarreja': ['Avanca', 'Beduído e Veiros', 'Canelas e Fermelã', 'Pardilhó'],
  'Ílhavo': [
    'Gafanha da Encarnação',
    'Gafanha da Nazaré',
    'Gafanha do Carmo',
    'Ílhavo (São Salvador)'
  ],
  'Mealhada': [
    'Barcouço',
    'Casal Comba',
    'Luso',
    'Mealhada, Ventosa do Bairro e Antes',
    'Pampilhosa',
    'Vacariça'
  ],
  'Murtosa': ['Bunheiro', 'Monte', 'Murtosa', 'Torreira'],
  'Oliveira de Azeméis': [
    'Carregosa',
    'Cesar',
    'Fajões',
    'Loureiro',
    'Macieira de Sarnes',
    'Nogueira do Cravo e Pindelo',
    'Oliveira de Azeméis, Santiago de Riba-Ul, Ul, Macinhata da Seixa e Madail',
    'Ossela',
    'Pinheiro da Bemposta, Travanca e Palmaz',
    'São Martinho da Gândara',
    'São Roque',
    'Vila de Cucujães'
  ],
  'Oliveira do Bairro': [
    'Bustos, Troviscal e Mamarrosa',
    'Oliveira do Bairro',
    'Oiã',
    'Palhaça'
  ],
  'Ovar': [
    'Cortegaça',
    'Esmoriz',
    'Maceda',
    'União das Freguesias de Ovar, São João, Arada e São Vicente de Pereira Jusã',
    'Válega'
  ],
  'Santa Maria da Feira': ['S. João da Madeira'],
  'Sever do Vouga': [
    'Cedrim e Paradela',
    'Couto de Esteves',
    'Pessegueiro do Vouga',
    'Rocas do Vouga',
    'Sever do Vouga',
    'Silva Escura e Dornelas',
    'Talhadas'
  ],
  'Vagos': [
    'Calvão',
    'Fonte de Angeão e Covão do Lobo',
    'Gafanha da Boa Hora',
    'Ouca',
    'Ponte de Vagos e Santa Catarina',
    'Santo André de Vagos',
    'Sosa',
    'Vagos e Santo António'
  ],
  'Vale de Cambra': [
    'Arões',
    'Cepelos',
    'Junqueira',
    'Macieira de Cambra',
    'Roge',
    'São Pedro de Castelões',
    'Vila Chã, Codal e Vila Cova de Perrinho'
  ],
  'Aljustrel': [
    'Aljustrel e Rio de Moinhos',
    'Ervidel',
    'Messejana',
    'São João de Negrilhos'
  ],
  'Almodôvar': [
    'Aljustrel e Rio de Moinhos',
    'Almodôvar e Graça dos Padrões',
    'Rosário',
    'São Barnabé',
    'Santa Clara-a-Nova e Gomes Aires',
    'Santa Cruz'
  ],
  'Barrancos': ['Freguesia de Barrancos'],
  'Beja': [
    'Albernoa e Trindade',
    'Baleizão',
    'Beja (Salvador e Santa Maria da Feira)',
    'Beja (Santiago Maior e São João Baptista)',
    'Beringel',
    'Cabeça Gorda',
    'Nossa Senhora das Neves',
    'Salvada e Quintos',
    'Santa Clara de Louredo',
    'Santa Vitória e Mombeja',
    'São Matias',
    'Trigaches e São Brisso'
  ],
  'Castro Verde': [
    'Castro Verde e Casével',
    'Entradas',
    'Santa Bárbara de Padrões',
    'São Marcos da Ataboeira'
  ],
  'Cuba': ['Cuba', 'Faro do Alentejo', 'Vila Alva', 'Vila Ruiva'],
  'Ferreira do Alentejo': [
    'Alfundão e Peroguarda',
    'Ferreira do Alentejo e Canhestros',
    'Figueira dos Cavaleiros',
    'Odivelas'
  ],
  'Mértola': [
    'Alcaria Ruiva',
    'Corte do Pinto',
    'Espírito Santo',
    'Mértola',
    'Santana de Cambas',
    'São João dos Caldeireiros',
    'São Miguel do Pinheiro, São Pedro de Solis e São Sebastião dos Carros'
  ],
  'Moura': [
    'Amareleja',
    'Moura (Santo Agostinho e São João Baptista) e Santo Amador',
    'Póvoa de São Miguel',
    'Safara e Santo Aleixo da Restauração',
    'Sobral da Adiça'
  ],
  'Odemira': [
    'Boavista dos Pinheiros',
    'Colos',
    'Longueira / Almograve',
    'Luzianes-Gare',
    'Relíquias',
    'Saboia',
    'Santa Clara-a-Velha',
    'São Luís',
    'São Martinho das Amoreiras',
    'São Salvador e Santa Maria',
    'São Teotónio',
    'Vale de Santiago',
    'Vila Nova de Milfontes'
  ],
  'Ourique': [
    'Garvão e Santa Luzia',
    'Ourique',
    'Panoias e Conceição',
    'Santana da Serra'
  ],
  'Serpa': [
    'Brinches',
    'Pias',
    'Serpa (Salvador e Santa Maria)',
    'Vila Nova de São Bento e Vale de Vargo',
    'Vila Verde de Ficalho'
  ],
  'Vidigueira': ['Pedrógão', 'Selmes', 'Vidigueira', 'Vila de Frades'],
  'Amares': [
    'Amares e Figueiredo',
    'Barreiros',
    'Bico',
    'Caires',
    'Caldelas, Sequeiros e Paranhos',
    'Carrazedo',
    'Dornelas',
    'Ferreiros, Prozelo e Besteiros',
    'Fiscal',
    'Goães',
    'Lago',
    'Rendufe',
    'Santa Maria do Bouro',
    'Santa Marta do Bouro',
    'Torre e Portela'
  ],
  'Barcelos': [
    'Abade de Neiva',
    'Aborim',
    'Adães',
    'Airó',
    'Aldreu',
    'Alheira e Igreja Nova',
    'Alvelos',
    'Alvito (São Pedro e São Martinho) e Couto',
    'Arcozelo',
    'Areias de Vilar e Encourados',
    'Areias S. Vicente',
    'Balugães',
    'Barcelinhos',
    'Barcelos, Vila Boa e Vila Frescaínha (São Martinho e São Pedro)',
    'Barqueiros',
    'Cambeses',
    'Campo e Tamel (São Pedro Fins)',
    'Carapeços',
    'Carreira e Fonte Coberta',
    'Carvalhal',
    'Carvalhas',
    'Chorente, Góios, Courel, Pedra Furada e Gueral',
    'Cossourado',
    'Creixomil e Mariz',
    'Cristelo',
    'Durrães e Tregosa',
    'Fornelos',
    'Fragoso',
    'Galegos S. Martinho',
    'Galegos Sta. Maria',
    'Gamil e Midões',
    'Gilmonde',
    'Lama',
    'Lijó',
    'Macieira de Rates',
    'Manhente',
    'Martim',
    'Milhazes, Vilar de Figos e Faria',
    'Moure',
    'Negreiros e Chavão',
    'Oliveira',
    'Palme',
    'Panque',
    'Paradela',
    'Pereira',
    'Perelhal',
    'Pousa',
    'Quintiães e Aguiar',
    'Remelhe',
    'Rio Côvo Sta. Eugénia',
    'Roriz',
    'Sequeade e Bastuço (São João e Santo Estevão)',
    'Silva',
    'Silveiros e Rio Covo (Santa Eulália)',
    'Tamel (Santa Leocádia) e Vilar do Monte',
    'Tamel S. Veríssimo',
    'Ucha',
    'Várzea',
    'Viatodos, Grimancelos, Minhotães e Monte de Fralães',
    'Vila Cova e Feitos',
    'Vila Seca'
  ],
  'Braga': [
    'Adaúfe',
    'Arentim e Cunha',
    'Braga (Maximinos, Sé e Cividade)',
    'Braga (São José de São Lázaro e São João do Souto)',
    'Cabreiros e Passos (São Julião)',
    'Celeirós, Aveleda e Vimieiro',
    'Crespos e Pousada',
    'Escudeiros e Penso (Santo Estêvão e São Vicente)',
    'Espinho',
    'Esporões',
    'Este (São Pedro e São Mamede)',
    'Ferreiros e Gondizalves',
    'Figueiredo',
    'Gualtar',
    'Guisande e Oliveira (São Pedro)',
    'Lamas',
    'Lomar e Arcos',
    'Merelim (São Paio), Panóias e Parada de Tibães',
    'Merelim (São Pedro) e Frossos',
    'Mire de Tibães',
    'Morreira e Trandeiras',
    'Nogueira, Fraião e Lamaçães',
    'Nogueiró e Tenões',
    'Padim da Graça',
    'Palmeira',
    'Pedralva',
    'Priscos',
    'Real, Dume e Semelhe',
    'Ruilhe',
    'Santa Lucrécia de Algeriz e Navarra',
    'São Vicente',
    'São Victor',
    'Sequeira',
    'Sobreposta',
    'Tadim',
    'Tebosa',
    'Vilaça e Fradelos'
  ],
  'Cabeceiras de Basto': [
    'Abadim',
    'Alvite e Passos',
    'Arco de Baúlhe e Vila Nune',
    'Basto',
    'Bucos',
    'Cabeceiras de Basto',
    'Cavez',
    'Faia',
    'Gondiães e Vilar de Cunhas',
    'Pedraça',
    'Refojos de Basto, Outeiro e Painzela',
    'Rio Douro'
  ],
  'Celorico de Basto': [
    'Agilde',
    'Arnoia',
    'Borba de Montanha',
    'Britelo, Gémeos e Ourilhe (Celorico de Basto)',
    'Caçarilhe e Infesta',
    'Canedo de Basto e Corgo',
    'Carvalho e Basto (Santa Tecla)',
    'Codeçoso',
    'Fervença',
    'Moreira do Castelo',
    'Rego',
    'Ribas',
    'São Clemente de Basto',
    'Vale de Bouro',
    'Veade, Gagos e Molares'
  ],
  'Esposende': [
    'Antas',
    'Apúlia e Fão',
    'Belinho e Mar',
    'Esposende, Marinhas e Gandra (Cidade)',
    'Fonte Boa e Rio Tinto',
    'Forjães',
    'Gemeses',
    'Palmeira de Faro e Curvos',
    'Vila Chã'
  ],
  'Fafe': [
    'Agrela e Serafão',
    'Antime e Silvares (São Clemente)',
    'Ardegão, Arnozela e Seidões',
    'Armil',
    'Cepães e Fareja',
    'Estorãos',
    'Fafe',
    'Fornelos',
    'Freitas e Vila Cova',
    'Golães',
    'Medelo',
    'Monte e Queimadela',
    'Moreira do Rei e Várzea Cova',
    'Passos',
    'Quinchães',
    'Regadas',
    'Revelhe',
    'Ribeiros',
    'Santa Cristina de Arões',
    'São Gens',
    'São Martinho de Silvares',
    'São Romão de Arões',
    'Travassós',
    'Vinhós'
  ],
  'Guimarães': [
    'Abação e Gémeos',
    'Airão Santa Maria, Airão São João e Vermil',
    'Aldão',
    'Arosa e Castelões',
    'Atães e Rendufe',
    'Azurém',
    'Barco',
    'Briteiros (Santo Estêvão) e Donim',
    'Briteiros (São Salvador e Santa Leocádia)',
    'Brito',
    'Caldelas',
    'Candoso (São Martinho)',
    'Candoso (São Tiago) e Mascotelos',
    'Conde e Gandarela',
    'Costa',
    'Creixomil',
    'Fermentões',
    'Gonça',
    'Gondar',
    'Guardizela',
    'Infantas',
    'Leitões, Oleiros e Figueiredo',
    'Longos',
    'Lordelo',
    'Mesão Frio',
    'Moreira de Cónegos',
    'Nespereira',
    'Oliveira, São Paio e São Sebastião',
    'Pencelo',
    'Pinheiro',
    'Polvoreira',
    'Ponte',
    'Prazins (Santa Eufémia)',
    'Prazins (Santo Tirso) e Corvite',
    'Ronfe',
    'Sande (São Lourenço) e Balazar',
    'Sande (São Martinho)',
    'Sande (Vila Nova e São Clemente)',
    'São Torcato',
    'Selho (São Cristóvão)',
    'Selho (São Jorge)',
    'Selho (São Lourenço) e Gominhães',
    'Serzedelo',
    'Serzedo e Calvos',
    'Silvares',
    'Souto e Gondomar',
    'Tabuadelo e São Faustino',
    'Urgezes'
  ],
  'Póvoa de Lanhoso': [
    'Águas Santas e Moure',
    'Calvos e Frades',
    'Campos e Louredo',
    'Covelas',
    'Esperança e Brunhais',
    'Ferreiros',
    'Fonte Arcada e Oliveira',
    'Galegos',
    'Garfe',
    'Geraz do Minho',
    'Lanhoso',
    'Monsul',
    'Póvoa de Lanhoso',
    'Rendufinho',
    'Santo Emilião',
    'São João de Rei',
    'Serzedelo',
    'Sobradelo da Goma',
    'Taíde',
    'Travassos',
    'Verim, Friande e Ajude',
    'Vilela'
  ],
  'Terras de Bouro': [
    'Balança',
    'Campo do Gerês',
    'Carvalheira',
    'Chamoim e Vilar',
    'Chorense e Monte',
    'Cibões e Brufe',
    'Covide',
    'Gondoriz',
    'Moimenta (sede)',
    'Ribeira',
    'Rio Caldo',
    'Souto',
    'Valdosende',
    'Vilar da Veiga'
  ],
  'Vieira do Minho': [
    'Anissó e Soutelo',
    'Anjos e Vilar Chão',
    'Caniçada e Soengas',
    'Cantelães',
    'Eira Vedra',
    'Guilhofrei',
    'Louredo',
    'Mosteiro',
    'Parada do Bouro',
    'Pinheiro',
    'Rossas',
    'Ruivães e Campos',
    'Salamonde',
    'Tabuaças',
    'Ventosa e Cova',
    'Vieira do Minho'
  ],
  'Vila Nova de Famalicão': [
    'Antas e Abade de Vermoim',
    'Arnoso (Santa Maria e Santa Eulália) e Sezures',
    'Bairro',
    'Brufe',
    'Carreira e Bente',
    'Castelões',
    'Cruz',
    'Delães',
    'Esmeriz e Cabeçudos',
    'Fradelos',
    'Gavião (Vila Nova de Famalicão)',
    'Gondifelos, Cavalões e Outiz',
    'Joane (vila)',
    'Landim',
    'Lemenhe, Mouquim e Jesufrei',
    'Louro',
    'Lousado',
    'Mogege',
    'Nine',
    'Oliveira (Santa Maria)',
    'Oliveira (São Mateus)',
    'Pousada de Saramagos',
    'Pedome',
    'Requião',
    'Riba de Ave (vila)',
    'Ribeirão (vila)',
    'Ruivães e Novais',
    'Seide',
    'Vale (São Cosme), Telhado e Portela',
    'Vale (São Martinho)',
    'Vermoim',
    'Vila Nova de Famalicão e Calendário',
    'Vilarinho das Cambas'
  ],
  'Vila Verde': [
    'Aboim da Nóbrega e Gondomar',
    'Atiães',
    'Cabanelas',
    'Carreiras (São Miguel) e Carreiras (Santiago)',
    'Cervães',
    'Coucieiro',
    'Penascais',
    'Codeceda',
    'Valões',
    'Godinhaços',
    'Covas',
    'Dossãos',
    'Escariz (São Mamede) e Escariz (São Martinho)',
    'Esqueiros, Nevogilde e Travassós',
    'Freiriz',
    'Gême',
    'Lage',
    'Lanhas',
    'Loureira',
    'Marrancos e Arcozelo',
    'Moure',
    'Oleiros',
    'Oriz (Santa Marinha) e Oriz (São Miguel)',
    'Parada de Gatim',
    'Pico (São Cristóvão)',
    'Pico de Regalados, Gondiães e Mós',
    'Ponte',
    'Sabariz',
    'Sande, Vilarinho, Barros e Gomide',
    'São Miguel do Prado',
    'Soutelo',
    'Turiz',
    'Ribeira do Neiva',
    'Vade',
    'Valbom (São Pedro), Passô e Valbom (São Martinho)',
    'Valdreu',
    'Vila de Prado',
    'Vila Verde e Barbudo'
  ],
  'Vizela': [
    'Caldas de Vizela (São Miguel e São João)',
    'Infias',
    'Santa Eulália',
    'Santo Adrião de Vizela',
    'Tagilde e Vizela (São Paio)'
  ],
  'Alfândega da Fé': [
    'Agrobom, Saldonha e Vale Pereiro',
    'Alfândega da Fé',
    'Cerejais',
    'Eucísia, Gouveia e Valverde',
    'Ferradosa e Sendim da Serra',
    'Gebelim e Soeima',
    'Parada e Sendim da Ribeira',
    'Pombal e Vales',
    'Sambade',
    'Vilar Chão',
    'Vilarelhos'
  ],
  'Bragança': [
    'Alfaião',
    'Aveleda e Rio de Onor',
    'Babe',
    'Baçal',
    'Carragosa',
    'Castrelos e Carrazedo',
    'Castro de Avelãs',
    'Coelhoso',
    'Donai',
    'Espinhosela',
    'França',
    'Gimonde',
    'Gondesende',
    'Gostei',
    'Grijó de Parada',
    'Izeda, Calvelhe e Paradinha Nova',
    'Macedo do Mato',
    'Mós',
    'Nogueira',
    'Outeiro',
    'Parada e Faílde',
    'Parâmio',
    'Pinela',
    'Quintanilha',
    'Quintela de Lampaças',
    'Rabal',
    'Rebordainhos e Pombares',
    'Rebordãos',
    'Rio Frio e Milhão',
    'Salsas',
    'Samil',
    'Santa Comba de Rossas',
    'São Julião de Palácios e Deilão',
    'São Pedro de Sarracenos',
    'Sé, Santa Maria e Meixedo',
    'Sendas',
    'Serapicos',
    'Sortes',
    'Zoio'
  ],
  'Carrazeda de Ansiães': [
    'Amedo e Zedes',
    'Belver e Mogo de Malta',
    'Carrazeda de Ansiães',
    'Castanheiro do Norte e Ribalonga',
    'Fonte Longa',
    'Lavandeira, Beira Grande e Selores',
    'Linhares',
    'Marzagão',
    'Parambos',
    'Pereiros',
    'Pinhal do Norte',
    'Pombal',
    'Seixo de Ansiães',
    'Vilarinho da Castanheira'
  ],
  'Freixo de Espada à Cinta': [
    'Freixo de Espada à Cinta e Mazouco',
    'Lagoaça e Fornos',
    'Ligares',
    'Poiares'
  ],
  'Macedo de Cavaleiros': [
    'Ala e Vilarinho do Monte',
    'Amendoeira',
    'Arcas',
    'Bornes e Burga',
    'Carrapatas',
    'Castelãos e Vilar do Monte',
    'Chacim',
    'Cortiços',
    'Corujas',
    'Espadanedo, Edroso, Murçós e Soutelo Mourisco',
    'Ferreira',
    'Grijó',
    'Lagoa',
    'Lamalonga',
    'Lamas',
    'Lombo',
    'Macedo de Cavaleiros',
    'Morais',
    'Olmos',
    'Peredo',
    'Podence e Santa Combinha',
    'Salselas',
    'Sezulfe',
    'Talhas',
    'Talhinhas e Bagueixe',
    'Vale Benfeito',
    'Vale da Porca',
    'Vale de Prados',
    'Vilarinho de Agrochão',
    'Vinhas'
  ],
  'Miranda do Douro': [
    'Aldendre',
    'Cedães',
    'Duas Igrejas',
    'Genísio',
    'Ifanes e Paradela',
    'Malhadas',
    'Miranda do Douro',
    'Palaçoulo',
    'Picote',
    'Póvoa',
    'São Martinho de Angueira',
    'Sendim e Atenor',
    'Silva e Águas Vivas',
    'Vila Chã de Braciosa'
  ],
  'Mirandela': [
    'Abambres',
    'Abreiro',
    'Aguieiras',
    'Alvites',
    'Avantos e Romeu',
    'Avidagos, Navalho e Pereira',
    'Barcel, Marmelos e Valverde da Gestosa',
    'Bouça',
    'Cabanelas',
    'Caravelas',
    'Carvalhais',
    'Cedães',
    'Cobro',
    'Fradizela',
    'Franco e Vila Boa',
    'Frechas',
    'Freixeda e Vila Verde',
    'Lamas de Orelhão',
    'Mascarenhas',
    'Mirandela',
    'Múrias',
    'Passos',
    'São Pedro Velho',
    'São Salvador',
    'Suçães',
    'Torre de Dona Chama',
    'Vale de Asnes',
    'Vale de Gouvinhas',
    'Vale de Salgueiro',
    'Vale de Telhas'
  ],
  'Mogadouro': [
    'Azinhoso',
    'Bemposta',
    'Bruçó',
    'Brunhoso',
    'Brunhozinho, Castanheira e Sanhoane',
    'Castelo Branco',
    'Castro Vicente',
    'Meirinhos',
    'Mogadouro, Valverde, Vale de Porco e Vilar de Rei',
    'Paradela',
    'Penas Roias',
    'Peredo da Bemposta',
    'Remondes e Soutelo',
    'Saldanha',
    'São Martinho do Peso',
    'Tó',
    'Travanca',
    'Urrós',
    'Vale da Madre',
    'Vila de Ala',
    'Vilarinho dos Galegos e Ventozelo'
  ],
  'Torre de Moncorvo': [
    'Açoreira',
    'Adeganha e Cardanha',
    'Cabeça Boa',
    'Carviçais',
    'Castedo',
    'Felgar e Souto da Velha',
    'Felgueiras e Maçores',
    'Horta da Vilariça',
    'Larinho',
    'Lousa',
    'Mós',
    'Torre de Moncorvo',
    'Urrós e Peredo dos Castelhanos'
  ],
  'Vila Flor': [
    'Assares e Lodões',
    'Benlhevai',
    'Candoso e Carvalho de Egas',
    'Freixiel',
    'Roios',
    'Samões',
    'Sampaio',
    'Santa Comba de Vilariça',
    'Seixo de Manhoses',
    'Trindade',
    'Vale Frechoso',
    'Valtorno e Mourão',
    'Vila Flor e Nabo',
    'Vilas Boas e Vilarinho das Azenhas'
  ],
  'Vimioso': [
    'Algoso, Campo de Víboras e Uva',
    'Argozelo',
    'Caçarelhos e Angueira',
    'Carção',
    'Matela',
    'Pinelo',
    'Santulhão',
    'Vale de Frades e Avelanoso',
    'Vilar Seco'
        'Vimioso'
  ],
  'Vinhais': [
    'Agrochão',
    'Candedo',
    'Celas',
    'Curopos e Vale de Janeiro',
    'Edral',
    'Edrosa',
    'Ervedosa',
    'Moimenta e Montouto',
    'Nunes e Ousilhão',
    'Paçó',
    'Penhas Juntas',
    'Quirás e Pinheiro Novo',
    'Rebordelo',
    'Santalha',
    'Sobreiró de Baixo e Alvaredos',
    'Soeira, Fresulfe e Mofreita',
    'Travanca e Santa Cruz',
    'Tuizelo',
    'Vale das Fontes',
    'Vila Boa de Ousilhão',
    'Vila Verde',
    'Vilar de Lomba e São Jomil',
    'Vilar de Ossos',
    'Vilar de Peregrinos',
    'Vilar Seco de Lomba',
    'Vinhais'
  ],
  'Belmonte': ['Belmonte e Colmeal da Torre', 'Caria', 'Inguias', 'Maçainhas'],
  'Castelo Branco': [
    'Alcains',
    'Almaceda',
    'Benquerenças',
    'Castelo Branco',
    'Cebolais de Cima e Retaxo',
    'Escalos de Baixo e Mata',
    'Escalos de Cima e Lousa',
    'Freixial e Juncal do Campo',
    'Lardosa',
    'Louriçal do Campo',
    'Malpica do Tejo',
    'Monforte da Beira',
    'Ninho do Açor e Sobral do Campo',
    'Póvoa de Rio de Moinhos e Cafede',
    'Salgueiro do Campo',
    'Santo André das Tojeiras',
    'São Vicente da Beira',
    'Sarzedas',
    'Tinalhas'
  ],
  'Covilhã': [
    'Aldeia de São Francisco de Assis',
    'Aldeia do Carvalho',
    'Aldeia do Souto',
    'Aldeia Nova do Cabo',
    'Aldeia Viçosa',
    'Barco e Coutada',
    'Boidobra',
    'Cantar-Galo e Vila do Carvalho',
    'Casegas e Ourondo',
    'Cortes do Meio',
    'Covilhã e Canhoso',
    'Dominguizo',
    'Erada',
    'Ferro',
    'Orjais',
    'Paul',
    'Peraboa',
    'Peso e Vales do Rio',
    'São Jorge da Beira',
    'Sobral de São Miguel',
    'Teixoso e Sarzedo',
    'Tortosendo',
    'Unhais da Serra',
    'Verdelhos'
  ],
  'Fundão': [
    'Alcaide',
    'Alcaria',
    'Alcongosta',
    'Alpedrinha',
    'Barroca',
    'Bogas de Cima',
    'Capinha',
    'Castelejo',
    'Castelo Novo',
    'Enxames',
    'Fatela',
    'Fundão, Valverde, Donas, Aldeia de Joanes e Aldeia Nova do Cabo',
    'Janeiro de Cima e Bogas de Baixo',
    'Lavacolhos',
    'Orca',
    'Pêro Viseu',
    'Póvoa de Atalaia e Atalaia do Campo',
    'Silvares',
    'Soalheira',
    'Souto da Casa',
    'Telhado',
    'Três Povos',
    'Vale de Prazeres e Mata da Rainha'
  ],
  'Idanha-a-Nova': [
    'Alcafozes',
    'Aldeia de Santa Margarida',
    'Idanha-a-Nova e Alcafozes',
    'Ladoeiro',
    'Medelim',
    'Monfortinho e Salvaterra do Extremo',
    'Monsanto e Idanha-a-Velha',
    'Oledo',
    'Penha Garcia',
    'Proença-a-Velha e Peral',
    'Rosmaninhal',
    'São Miguel de Acha',
    'Toulões',
    'Zebreira'
  ],
  'Oleiros': [
    'Álvaro',
    'Cambas',
    'Estreito-Vilar Barroco',
    'Isna',
    'Madeirã',
    'Mosteiro',
    'Oleiros-Amieira',
    'Orvalho',
    'Sarnadas de São Simão',
    'Sobral',
    'Vila Facaia'
  ],
  'Penamacor': [
    'Aldeia do Bispo, Águas e Aldeia de João Pires',
    'Aranhas',
    'Benquerença',
    'Meimão',
    'Meimoa',
    'Penamacor',
    'Salvador',
    'Vale da Senhora da Póvoa',
    'Vale de Madeira'
  ],
  'Proença-a-Nova': [
    'Montes da Senhora',
    'Proença-a-Nova e Peral',
    'Sobreira Formosa e Alvito da Beira',
    'São Pedro do Esteval',
    'São Simão',
    'Vila de Rei'
  ],
  'Sertã': [
    'Cabeçudo',
    'Carvalhal',
    'Castelo',
    'Cernache do Bonjardim, Nesperal e Palhais',
    'Cumeada e Marmeleiro',
    'Ermida e Figueiredo',
    'Ferraria de São João',
    'Mação, Penhascoso e Aboboreira',
    'Marmeleira e São João',
    'Maxial e Meimoa',
    'Pedrógão Pequeno',
    'Sertã',
    'Troviscal'
  ],
  'Vila de Rei': ['Fundada', 'São João do Peso', 'Vila de Rei'],
  'Vila Velha de Ródão': [
    'Fratel',
    'Perais',
    'Sarnadas de Ródão',
    'Vila Velha de Ródão'
  ],
  'Arganil': [
    'Arganil',
    'Benfeita',
    'Celavisa',
    'Cepos e Teixeira',
    'Cerdeira e Moura da Serra',
    'Côja e Barril de Alva',
    'Folques',
    'Pomares',
    'Pombeiro da Beira',
    'São Martinho da Cortiça',
    'Sarzedo',
    'Secarias',
    'Vila Cova de Alva e Anseriz',
  ],
  'Cantanhede': [
    'Ançã',
    'Bolho',
    'Cadima',
    'Camarneira e Vilar',
    'Cantanhede e Pocariça',
    'Cordinhã',
    'Covões e Camarneira',
    'Febres',
    'Murtede',
    'Ourentã',
    'Outil',
    'Portunhos e Outil',
    'Sanguinheira',
    'São Caetano',
    'São Lourenço do Bairro',
    'Sepins e Bolho',
    'Tocha',
    'Vilamar e Corticeiro de Cima'
  ],
  'Coimbra': [
    'Almalaguês',
    'Antuzede e Vil de Matos',
    'Assafarge e Antanhol',
    'Brasfemes',
    'Ceira',
    'Cernache',
    'Eiras e São Paulo de Frades',
    'Santa Clara e Castelo Viegas',
    'Santo António dos Olivais',
    'São Martinho de Árvore e Lamarosa',
    'São Martinho do Bispo e Ribeira de Frades',
    'Souselas e Botão',
    'Torres do Mondego',
    'Trouxemil e Torre de Vilela'
  ],
  'Condeixa-a-Nova': [
    'Anobra',
    'Condeixa-a-Nova e Condeixa-a-Velha',
    'Ega',
    'Furadouro',
    'Sebal e Belide',
    'Vila Seca e Bem da Fé',
  ],
  'Figueira da Foz': [
    'Alhadas',
    'Alqueidão',
    'Bom Sucesso',
    'Buarcos e São Julião',
    'Ferreira-a-Nova',
    'Lavos',
    'Maiorca',
    'Marinha das Ondas',
    'Moinhos da Gândara',
    'Paião',
    'Quiaios',
    'São Pedro',
    'Tavarede',
    'Vila Verde',
  ],
  'Góis': [
    'Alvares',
    'Cadafaz e Colmeal',
    'Góis',
    'Vila Nova do Ceira',
  ],
  'Lousã': [
    'Casal de Ermio',
    'Foz de Arouce e Casal de Ermio',
    'Gândaras',
    'Lousã e Vilarinho',
    'Serpins',
  ],
  'Mira': [
    'Carapelhos',
    'Mira',
    'Praia de Mira',
    'Seixo',
    'Vide e Ventosa',
  ],
  'Miranda do Corvo': [
    'Lamas',
    'Miranda do Corvo',
    'Rio Vide e Pereira',
    'Semide e Rio Vide',
    'Vila Nova',
  ],
  'Montemor-o-Velho': [
    'Abrunheira, Verride e Vila Nova da Barca',
    'Arazede',
    'Carapinheira',
    'Ereira',
    'Liceia',
    'Meãs do Campo',
    'Montemor-o-Velho e Gatões',
    'Pereira',
    'Santo Varão',
    'Seixo de Gatões',
    'Tentúgal',
  ],
  'Oliveira do Hospital': [
    'Aldeia das Dez',
    'Alvoco das Várzeas',
    'Avô',
    'Bobadela',
    'Ervedal e Vila Franca da Beira',
    'Lagares da Beira',
    'Lagos da Beira e Lajeosa',
    'Lourosa',
    'Meruge',
    'Nogueira do Cravo e Póvoa das Quartas',
    'Oliveira do Hospital e São Paio de Gramaços',
    'Penalva de Alva e São Sebastião da Feira',
    'Santa Ovaia e Vila Pouca da Beira',
    'São Gião',
    'Seixo da Beira',
    'Travanca de Lagos',
    'Vila Nova de Oliveirinha',
  ],
  'Pampilhosa da Serra': [
    'Cabril',
    'Dornelas do Zêzere',
    'Fajão-Vidual',
    'Janeiro de Baixo e Vila Cova de Alva',
    'Pampilhosa da Serra e Pessegueiro',
    'Portela do Fojo-Machio',
    'Unhais-o-Velho',
  ],
  'Penacova': [
    'Carvalho',
    'Figueira de Lorvão',
    'Friúmes e Paradela',
    'Lorvão',
    'Oliveira do Mondego e Travanca do Mondego',
    'Penacova',
    'São Pedro de Alva e São Paio do Mondego',
    'Sazes do Lorvão',
  ],
  'Penela': [
    'Cumeeira',
    'Espinhal',
    'Podentes',
    'Rabaçal',
    'Santa Eufémia e Rabaçal',
    'São Miguel, Santa Eufémia e Rabaçal',
    'São Simão de Litém e Albergaria dos Doze',
  ],
  'Soure': [
    'Alfarelos',
    'Degracias e Pombalinho',
    'Figueiró do Campo',
    'Granja do Ulmeiro',
    'Samuel',
    'Soure',
    'Tapéus',
    'Vila Nova de Anços',
  ],
  'Tábua': [
    'Ázere e Covelo',
    'Candosa',
    'Carapinha',
    'Covas e Vila Nova de Oliveirinha',
    'Espariz e Sinde',
    'Mouronho',
    'Pinheiro de Coja e Meda de Mouros',
    'Póvoa de Midões',
    'São João da Boa Vista',
    'Tábua',
    'Vila Nova de Oliveirinha',
  ],
  'Vila Nova de Poiares': [
    'Arrifana',
    'Lavegadas',
    'Poiares (Santo André)',
    'Poiares (São Miguel)',
    'São Miguel de Poiares',
    'São Miguel de Poiares',
  ],
  'Alandroal': [
    'Alandroal (Nossa Senhora da Conceição), São Brás dos Matos (Mina do Bugalho) e Juromenha (Nossa Senhora do Loreto)',
    'Capelins (Santo António)',
    'Santiago Maior',
    'Terena (São Pedro)',
  ],
  'Arraiolos': [
    'Arraiolos',
    'Gafanhoeira (São Pedro) e Sabugueiro',
    'Igrejinha',
    'São Gregório e Santa Justa',
    'Vimieiro',
  ],
  'Borba': [
    'Borba (Matriz)',
    'Borba (São Bartolomeu)',
    'Orada',
    'Rio de Moinhos',
  ],
  'Estremoz': [
    'Arcos',
    'Estremoz (Santa Maria e Santo André)',
    'Évora Monte (Santa Maria)',
    'Glória',
    'São Bento do Cortiço e Santo Estêvão',
    'São Domingos de Ana Loura',
    'Veiros',
  ],
  'Évora': [
    'Bacelo e Senhora da Saúde',
    'Canaviais',
    'Évora (São Mamede, Sé, São Pedro e Santo Antão)',
    'Malagueira e Horta das Figueiras',
    'Nossa Senhora da Graça do Divor',
    'Nossa Senhora da Tourega e Nossa Senhora de Guadalupe',
    'Nossa Senhora de Machede',
    'São Bento do Mato',
    'São Manços e São Vicente do Pigeiro',
    'São Miguel de Machede',
    'São Sebastião da Giesteira e Nossa Senhora da Boa Fé',
    'Torre de Coelheiros',
  ],
  'Montemor-o-Novo': [
    'Ciborro',
    'Cortiçadas de Lavre e Lavre',
    'Foros de Vale de Figueira',
    'Nossa Senhora da Vila, Nossa Senhora do Bispo e Silveiras',
    'Santiago do Escoural',
    'São Cristóvão',
  ],
  'Mora': [
    'Brotas',
    'Cabeção',
    'Mora',
    'Pavia',
    'Ponte de Sor, Tramaga e Vale de Açor',
  ],
  'Mourão': [
    'Granja',
    'Luz',
    'Mourão',
    'Safara e Santo Aleixo da Restauração',
  ],
  'Portel': [
    'Amieira e Alqueva',
    'Monte do Trigo',
    'Portel',
    'Santana',
    'Vera Cruz',
  ],
  'Redondo': [
    'Montoito',
    'Redondo',
    'São Vicente de Alcáçovas',
    'Vila Viçosa',
  ],
  'Reguengos de Monsaraz': [
    'Campo e Campinho',
    'Corval',
    'Monsaraz',
    'Reguengos de Monsaraz',
  ],
  'Vendas Novas': ['Landeira', 'Vendas Novas'],
  'Viana do Alentejo': [
    'Aguiar',
    'Alcáçovas',
    'Viana do Alentejo',
  ],
  'Vila Viçosa': [
    'Bencatel',
    'Ciladas',
    'Pardais',
    'São Bartolomeu',
    'Vila Viçosa',
  ],
  'Albufeira': [
    'Albufeira e Olhos de Água',
    'Ferreiras',
    'Guia',
    'Paderne',
  ],
  'Alcoutim': [
    'Alcoutim e Pereiro',
    'Giões',
    'Martim Longo',
    'Vaqueiros',
  ],
  'Aljezur': [
    'Aljezur',
    'Bordeira',
    'Odeceixe',
    'Rogil',
  ],
  'Castro Marim': [
    'Altura',
    'Azinhal',
    'Castro Marim',
    'Odeleite',
  ],
  'Faro': [
    'Conceição e Estoi',
    'Faro (Sé e São Pedro)',
    'Montenegro',
    'Santa Bárbara de Nexe',
  ],
  'Lagoa': [
    'Estômbar e Parchal',
    'Ferragudo',
    'Lagoa e Carvoeiro',
    'Porches',
  ],
  'Lagos': [
    'Bensafrim e Barão de São João',
    'Luz',
    'Odiáxere',
    'Santa Maria',
    'São Gonçalo de Lagos',
  ],
  'Loulé': [
    'Almancil',
    'Alte',
    'Ameixial',
    'Boliqueime',
    'Quarteira',
    'Querença, Tôr e Benafim',
    'Salir',
    'São Clemente',
    'São Sebastião',
    'União de freguesias de Almancil e Pereiras',
    'União de freguesias de Querença, Tôr e Benafim',
    'União de freguesias de São Sebastião e Santa Maria',
    'União de freguesias de Quarteira e Vilamoura',
  ],
  'Monchique': [
    'Alferce',
    'Marmelete',
    'Monchique',
  ],
  'Olhão': [
    'Fuseta',
    'Moncarapacho e Fuseta',
    'Olhão',
    'Pechão',
    'Quelfes',
  ],
  'Portimão': [
    'Alvor',
    'Mexilhoeira Grande',
    'Portimão',
  ],
  'São Brás de Alportel': [
    'São Brás de Alportel',
  ],
  'Silves': [
    'Alcantarilha e Pêra',
    'Algoz e Tunes',
    'Armação de Pêra',
    'São Bartolomeu de Messines',
    'São Marcos da Serra',
    'Silves',
  ],
  'Tavira': [
    'Cabanas de Tavira',
    'Cachopo',
    'Conceição e Cabanas de Tavira',
    'Luz de Tavira e Santo Estêvão',
    'Santa Catarina da Fonte do Bispo',
    'Santa Luzia',
    'Tavira (Santa Maria e Santiago)',
  ],
  'Vila do Bispo': [
    'Barão de São Miguel',
    'Budens',
    'Raposeira',
    'Sagres',
    'Vila do Bispo e Raposeira',
  ],
  'Vila Real de Santo António': [
    'Monte Gordo',
    'Vila Nova de Cacela',
    'Vila Real de Santo António',
  ],
  'Aguiar da Beira': [
    'Aguiar da Beira e Coruche',
    'Carapito',
    'Cortiçada',
    'Dornelas',
    'Eirado',
    'Forninhos',
    'Pena Verde',
    'Pinheiro',
    'Sequeiros e Gradiz',
    'Souto de Aguiar da Beira e Valverde',
  ],
  'Almeida': [
    'Almeida',
    'Castelo Bom',
    'Freineda',
    'Freixo',
    'Junça e Naves',
    'Leomil',
    'Malhada Sorda',
    'Malpartida',
    'Mesquitela',
    'Mido',
    'Miuzela e Porto de Ovelha',
    'Nave de Haver',
    'São Pedro de Rio Seco',
    'Senouras e Aldeia Nova',
    'Terras de Almeida',
    'Vale da Mula',
    'Vale de Coelha e Matacães',
    'Vilar Formoso',
  ],
  'Celorico da Beira': [
    'Baraçal',
    'Carrapichana',
    'Casas do Soeiro',
    'Celorico (São Pedro e Santa Maria) e Vila Boa do Mondego',
    'Forno Telheiro',
    'Lajeosa do Mondego',
    'Linhares',
    'Maçal do Chão',
    'Mesquitela',
    'Minhocal',
    'Prados',
    'Rapa e Cadafaz',
    'Ratoeira',
    'Vale de Azares',
    'Velosa',
  ],
  'Figueira de Castelo Rodrigo': [
    'Algodres, Vale de Afonsinho e Vilar de Amargo',
    'Almofala e Escarigo',
    'Castelo Rodrigo',
    'Cinco Vilas e Reigada',
    'Colmeal e Vilar Torpim',
    'Escalhão',
    'Figueira de Castelo Rodrigo',
    'Freixeda do Torrão, Quintã de Pêro Martins e Penha de Águia',
    'Mata de Lobos',
    'Vermiosa',
  ],
  'Fornos de Algodres': [
    'Algodres, Vale de Afonsinho e Vilar de Amargo',
    'Casal Vasco',
    'Cortiçô e Vila Chã',
    'Figueiró da Granja',
    'Fornos de Algodres e Casal Vasco',
    'Infias',
    'Maceira',
    'Matança',
    'Muxagata',
    'Queiriz',
    'Sobral Pichorro e Fuinhas',
  ],
  'Gouveia': [
    'Aldeias e Mangualde da Serra',
    'Arcozelo',
    'Cativelos',
    'Figueiró da Serra e Freixo da Serra',
    'Folgosinho',
    'Gouveia (São Pedro e São Julião)',
    'Melão',
    'Moimenta da Serra e Vinhó',
    'Nespereira',
    'Paços da Serra',
    'Ribamondego',
    'Rio Torto e Lagarinhos',
    'São Paio',
    'Vila Cortês da Serra',
  ],
  'Guarda': [
    'Adão',
    'Aldeia do Bispo, Águas e Aldeia de João Pires',
    'Aldeia Viçosa',
    'Alvendre e Lourosa',
    'Arrifana',
    'Avelãs da Ribeira, Chãs, Vide e Salgueirais',
    'Avelãs de Ambom e Rocamondo',
    'Benespera',
    'Casal de Cinza',
    'Castanheira',
    'Cavadoude',
    'Codesseiro',
    'Corujeira e Trinta',
    'Faia',
    'Famalicão',
    'Fernão Joanes',
    'Gonçalo',
    'Guarda',
    'Jarmelo São Miguel',
    'Jarmelo São Pedro',
    'João Antão',
    'Maçainhas',
    'Marmeleiro',
    'Meios',
    'Panoias de Cima',
    'Pega',
    'Pêra do Moço',
    'Pêro Soares',
    'Porto da Carne',
    'Pousade e Albardo',
    'Ramela',
    'Rochoso e Monte Margarida',
    'Santana da Azinha',
    'São Miguel da Guarda',
    'São Miguel de Jarmelo',
    'Sobral da Serra',
    'Vale de Estrela',
    'Valhelhas',
    'Vela',
    'Videmonte',
    'Vila Cortês do Mondego',
    'Vila Fernando',
    'Vila Franca do Deão',
  ],
  'Manteigas': [
    'Sameiro',
    'Santa Maria',
    'São Pedro',
    'Vale de Amoreira',
  ],
  'Mêda': [
    'Aveloso',
    'Barreira',
    'Coriscada',
    'Longroiva',
    'Marialva',
    'Mêda, Outeiro de Gatos e Fonte Longa',
    'Poço do Canto',
    'Prova e Casteição',
    'Rabaçal',
    'Ranhados',
    'Vale Flor, Carvalhal e Pai Penela',
    'Vale da Senhora da Póvoa',
  ],
  'Pinhel': [
    'Alverca da Beira e Martinchel',
    'Atalaia e Safurdão',
    'Azevo e Parada',
    'Bouça Cova',
    'Cerejo',
    'Cidadelhe',
    'Ervas Tenras',
    'Freixedas',
    'Gouveias',
    'Lamegal',
    'Lameiras',
    'Manigoto',
    'Pala',
    'Pinhel',
    'Pínzio',
    'Souro Pires',
    'Souto Maior',
    'Valbom e Granja',
    'Vascoveiro',
  ],
  'Sabugal': [
    'Águas Belas, Aldeia do Bispo e Águas Vivas',
    'Aldeia da Ponte',
    'Aldeia da Ribeira, Vilar Maior e Badamalos',
    'Aldeia de Santo António',
    'Aldeia do Bispo',
    'Aldeia Velha',
    'Alfaiates',
    'Baraçal',
    'Bendada',
    'Bismula',
    'Casteleiro',
    'Cerdeira do Côa',
    'Fóios',
    'Forcalhos',
    'Lajeosa',
    'Lombal',
    'Malcata',
    'Nave',
    'Quadrazais',
    'Quintas de São Bartolomeu',
    'Rapoula do Côa',
    'Rebolosa',
    'Rendo',
    'Ruivós',
    'Sabugal e Aldeia de Santo António',
    'Santo Estêvão e Moita',
    'Seixo do Côa e Vale Longo',
    'Sortelha',
    'Souto',
    'Vale das Éguas',
    'Vale de Espinho',
    'Vale de Espinho e Mata',
    'Vilar Maior',
  ],
  'Seia': [
    'Aldeias e Mangualde da Serra',
    'Alvoco da Serra',
    'Cabeça',
    'Carragozela e Várzea de Meruge',
    'Carrapichana',
    'Ervedal e Vila Franca da Beira',
    'Girabolhos',
    'Lajes',
    'Lapa dos Dinheiros',
    'Loriga',
    'Paranhos',
    'Pinhanços',
    'Sabugueiro',
    'Sameice e Santa Eulália',
    'Sandomil',
    'Santa Comba',
    'Santa Marinha e São Martinho',
    'Santa Marinha e São Martinho',
    'Santiago',
    'Sazes da Beira',
    'Seia, São Romão e Lapa dos Dinheiros',
    'Teixeira',
    'Torrozelo e Folhadosa',
    'Tourais e Lajes',
    'Travancinha',
    'Valezim',
    'Vide e Cabeça',
  ],
  'Trancoso': [
    'Aldeia Nova',
    'Cerdeira',
    'Cernache',
    'Freches e Torres',
    'Granja',
    'Guilheiro',
    'Moimentinha',
    'Moreira de Rei e Vila Franca das Naves',
    'Palhais',
    'Póvoa do Concelho',
    'Reboleiro',
    'Rio de Mel',
    'São Pedro do Rio Seco',
    'Torre do Terrenho, Sebadelhe da Serra e Terrenho',
    'Torres',
    'Trancoso (São Pedro e Santa Maria) e Souto Maior',
    'Valdujo',
    'Vale do Seixo e Vila Garcia',
    'Vila Franca das Naves e Feital',
  ],
  'Vila Nova de Foz Côa': [
    'Almendra',
    'Castelo Melhor',
    'Cedovim',
    'Chãs',
    'Custóias',
    'Freixo de Numão',
    'Horta',
    'Mós',
    'Murça',
    'Numão',
    'Santa Comba',
    'Sebadelhe',
    'Seixas',
    'Touça',
    'Vila Nova de Foz Côa',
    'Vilar de Besteiros',
  ],
  'Alcobaça': [
    'Alcobaça e Vestiaria',
    'Alfeizerão',
    'Bárrio',
    'Benedita',
    'Cela',
    'Cós, Alpedriz e Montes',
    'Évora de Alcobaça',
    'Maiorga',
    'Pataias e Martingança',
    'São Martinho do Porto',
    'Turquel',
    'Vimeiro',
  ],
  'Alenquer': [
    'Abrigada e Cabanas de Torres',
    'Aldeia Galega da Merceana e Aldeia Gavinha',
    'Alenquer (Santo Estêvão e Triana)',
    'Carnota',
    'Carregado e Cadafais',
    'Meca',
    'Olhalvo',
    'Ota',
    'Ribafria e Pereiro de Palhacana',
    'Ventosa',
  ],
  'Amadora': [
    'Alfragide',
    'Encosta do Sol',
    'Falagueira-Venda Nova',
    'Mina de Água',
    'Venteira'
  ],
  'Arruda dos Vinhos': [
    'Arranhó',
    'Arruda dos Vinhos',
    'Cardosas',
    'Santiago dos Velhos',
    'São Tiago dos Velhos',
  ],
  'Azambuja': [
    'Alcoentre',
    'Aveiras de Baixo',
    'Aveiras de Cima',
    'Azambuja',
    'Manique do Intendente, Vila Nova de São Pedro e Maçussa',
    'Vale do Paraíso',
    'Vila Nova da Rainha'
  ],
  'Cadaval': [
    'Alguber',
    'Cadaval e Pêro Moniz',
    'Lamas e Cercal',
    'Painho e Figueiros',
    'Peral',
    'Vermelha',
  ],
  'Cascais': [
    'Alcabideche',
    'Carcavelos e Parede',
    'Cascais e Estoril',
    'São Domingos de Rana',
  ],
  'Lisboa': [
    'Ajuda',
    'Alcântara',
    'Alvalade',
    'Areeiro',
    'Arroios',
    'Avenidas Novas',
    'Beato',
    'Belém',
    'Benfica',
    'Campo de Ourique',
    'Campolide',
    'Carnide',
    'Estrela',
    'Lumiar',
    'Marvila',
    'Misericórdia',
    'Olivais',
    'Parque das Nações',
    'Penha de França',
    'Santa Clara',
    'Santa Maria Maior',
    'Santo António',
    'São Domingos de Benfica',
    'São Vicente',
  ],
  'Loures': [
    'Bucelas',
    'Fanhões',
    'Loures',
    'Lousa',
    'Moscavide e Portela',
    'Sacavém e Prior Velho',
    'Santa Iria de Azoia, São João da Talha e Bobadela',
    'Santo Antão e São Julião do Tojal',
    'Santo António dos Cavaleiros e Frielas'
  ],
  'Lourinhã': [
    'Lourinhã e Atalaia',
    'Miragaia e Marteleira',
    'Moita dos Ferreiros',
    'Reguengo Grande',
    'Ribamar',
    'Santa Bárbara',
    'São Bartolomeu dos Galegos e Moledo',
    'Vimeiro',
  ],
  'Mafra': [
    'Azueira e Sobral da Abelheira',
    'Carvoeira',
    'Encarnação',
    'Enxara do Bispo, Gradil e Vila Franca do Rosário',
    'Ericeira',
    'Igreja Nova e Cheleiros',
    'Mafra',
    'Malveira e São Miguel de Alcainça',
    'Milharado',
    'Santo Isidoro',
    'Sobral de Monte Agraço',
    'Venda do Pinheiro e Santo Estêvão das Galés',
  ],
  'Odivelas': [
    'Famões',
    'Odivelas',
    'Olival Basto',
    'Pontinha e Famões',
    'Póvoa de Santo Adrião e Olival Basto',
    'Ramada e Caneças',
  ],
  'Oeiras': [
    'Algés, Linda-a-Velha e Cruz Quebrada-Dafundo',
    'Barcarena',
    'Carnaxide e Queijas',
    'Oeiras e São Julião da Barra, Paço de Arcos e Caxias',
    'Porto Salvo',
  ],
  'Sintra': [
    'Agualva e Mira-Sintra',
    'Algueirão-Mem Martins',
    'Almargem do Bispo, Pêro Pinheiro e Montelavar',
    'Cacém e São Marcos',
    'Casal de Cambra',
    'Colares',
    'Massamá e Monte Abraão',
    'Queluz e Belas',
    'Rio de Mouro',
    'São João das Lampas e Terrugem',
    'Sintra (Santa Maria e São Miguel, São Martinho e São Pedro de Penaferrim)',
  ],
  'Sobral de Monte Agraço': [
    'Santo Quintino',
    'Sapataria',
    'Sobral de Monte Agraço',
  ],
  'Torres Vedras': [
    'A dos Cunhados e Maceira',
    'Campelos e Outeiro da Cabeça',
    'Carvoeira e Carmões',
    'Dois Portos e Runa',
    'Freiria',
    'Maxial e Monte Redondo',
    'Ponte do Rol',
    'Ramalhal',
    'Santa Maria, São Pedro e Matacães',
    'Silveira',
    'São Pedro da Cadeira',
    'Turcifal',
    'Ventosa',
  ],
  'Vila Franca de Xira': [
    'Alhandra, São João dos Montes e Calhandriz',
    'Alverca do Ribatejo e Sobralinho',
    'Castanheira do Ribatejo e Cachoeiras',
    'Póvoa de Santa Iria e Forte da Casa',
    'Vialonga',
    'Vila Franca de Xira',
  ],
  'Alter do Chão': [
    'Alter do Chão',
    'Chancelaria',
    'Cunheira',
    'Seda',
    'Seroa',
  ],
  'Arronches': [
    'Assunção',
    'Esperança',
    'Mosteiros',
    'Santo António',
  ],
  'Avis': [
    'Alcórrego e Maranhão',
    'Aldeia Velha',
    'Avis',
    'Benavila e Valongo',
    'Ervedal',
    'Figueira e Barros',
    'Olho Marinho',
    'Ponte de Sor, Tramaga e Vale de Açor',
    'São Bento do Cortiço e Santo Estêvão',
    'Sousel',
  ],
  'Campo Maior': [
    'Nossa Senhora da Expectação',
    'Nossa Senhora da Graça dos Degolados',
    'São João Baptista',
  ],
  'Castelo de Vide': [
    'Nossa Senhora da Graça de Póvoa e Meadas',
    'Santa Maria da Devesa',
    'Santiago Maior',
  ],
  'Crato': [
    'Aldeia da Mata',
    'Crato e Mártires, Flor da Rosa e Vale do Peso',
    'Gáfete',
    'Monte da Pedra',
  ],
  'Elvas': [
    'Ajuda, Salvador e Santo Ildefonso',
    'Alcáçova',
    'Assunção, Ajuda, Salvador e Santo Ildefonso',
    'Barbacena e Vila Fernando',
    'Caia, São Pedro e Alcáçova',
    'Santa Eulália',
    'São Brás e São Lourenço',
    'São Vicente e Ventosa',
    'Terrugem e Vila Boim',
  ],
  'Fronteira': [
    'Cabeço de Vide',
    'Fronteira',
    'São Saturnino',
  ],
  'Gavião': [
    'Belver',
    'Comenda',
    'Gavião e Atalaia',
    'Margem',
  ],
  'Marvão': [
    'Beirã',
    'Santa Maria de Marvão',
    'Santo António das Areias',
  ],
  'Monforte': [
    'Assumar',
    'Monforte',
    'Santo Aleixo',
    'Vaiamonte',
  ],
  'Nisa': [
    'Alpalhão',
    'Arez e Amieira do Tejo',
    'Espírito Santo, Nossa Senhora da Graça e São Simão',
    'Montalvão',
    'Santana',
    'São Matias',
    'Tolosa',
  ],
  'Ponte de Sor': [
    'Foros de Arrão',
    'Galveias',
    'Longomel',
    'Montargil',
    'Ponte de Sor, Tramaga e Vale de Açor',
  ],
  'Portalegre': [
    'Alagoa',
    'Alegrete',
    'Fortios',
    'Reguengo e São Julião',
    'Ribeira de Nisa e Carreiras',
    'Sé e São Lourenço',
    'Urra',
  ],
  'Sousel': [
    'Cano',
    'Casa Branca',
    'Santo Amaro',
    'Sousel',
  ],
  'Amarante': [
    'Aboadela, Sanche e Várzea',
    'Amarante (São Gonçalo), Madalena, Cepelos e Gatão',
    'Ansiães',
    'Bustelo, Carneiro e Carvalho de Rei',
    'Candemil',
    'Figueiró (Santiago e Santa Cristina)',
    'Fregim',
    'Freixo de Cima e de Baixo',
    'Fridão',
    'Gondar',
    'Jazente',
    'Lomba',
    'Louredo',
    'Lufrei',
    'Mancelos',
    'Olo e Canadelo',
    'Padronelo',
    'Rebordelo',
    'Salvador do Monte',
    'São Simão de Gouveia',
    'Telões',
    'Travanca',
    'Vila Caiz',
    'Vila Chã do Marão',
    'Vila Garcia, Aboim e Chapa',
    'Vila Meã (Real, Ataíde e Oliveira)',
  ],
  'Baião': [
    'Ancede e Ribadouro',
    'Baião (Santa Leocádia) e Mesquinhata',
    'Campelo e Ovil',
    'Freixo de Baixo e de Cima',
    'Gestaçô',
    'Gove',
    'Grilo',
    'Loivos da Ribeira e Tresouras',
    'Loivos do Monte',
    'Santa Cruz do Douro e São Tomé de Covelas',
    'Teixeira e Teixeiró',
  ],
  'Felgueiras': [
    'Aião',
    'Airães',
    'Friande',
    'Idães',
    'Jugueiros',
    'Lagares e Figueira',
    'Lordelo',
    'Macieira da Lixa e Caramos',
    'Margaride (Santa Eulália), Várzea, Lagares, Varziela e Moure',
    'Pedreira, Rande e Sernande',
    'Penacova',
    'Pinheiro',
    'Pombeiro de Ribavizela',
    'Refontoura',
    'Regilde',
    'Revinhade',
    'Sendim',
    'Sernande',
    'Torre de Vilela',
    'Torrados e Sousa',
    'Unhão e Lordelo',
    'Varziela',
  ],
  'Gondomar': [
    'Baguim do Monte (Rio Tinto)',
    'Fânzeres e São Pedro da Cova',
    'Foz do Sousa e Covelo',
    'Gondomar (São Cosme), Valbom e Jovim',
    'Lomba',
    'Melres e Medas',
    'Rio Tinto',
    'São Pedro da Cova',
    'Valbom',
  ],
  'Lousada': [
    'Aveleda',
    'Caíde de Rei',
    'Casais',
    'Cernadelo e Lousada (São Miguel e Santa Margarida)',
    'Cristelos, Boim e Ordem',
    'Figueiras e Covas',
    'Lodares',
    'Lousada (São Pedro e Santo Estevão)',
    'Macieira',
    'Meinedo',
    'Nespereira e Casais',
    'Nevogilde',
    'Nogueira',
    'Sousela',
    'Torno',
    'Vilar do Torno e Alentém',
  ],
  'Maia': [
    'Águas Santas',
    'Barca',
    'Folgosa',
    'Gemunde',
    'Gondim',
    'Gueifães',
    'Maia',
    'Milheirós',
    'Moreira',
    'Nogueira e Silva Escura',
    'Pedrouços',
    'São Pedro Fins',
    'Vermoim',
  ],
  'Marco de Canaveses': [
    'Alpendorada, Várzea e Torrão',
    'Avessadas e Rosém',
    'Banho e Carvalhosa',
    'Constance',
    'Folhada',
    'Fornos',
    'Freixo',
    'Lomba',
    'Magrelos',
    'Paredes de Viadores e Manhuncelos',
    'Paredes e São Vicente de Sousa',
    'Penha Longa e Paços de Gaiolo',
    'Rio de Galinhas',
    'Sande e São Lourenço do Douro',
    'Santo Isidoro e Livração',
    'São Nicolau',
    'Soalhães',
    'Tabuado',
    'Várzea, Aliviada e Folhada',
  ],
  'Matosinhos': [
    'Custóias, Leça do Balio e Guifões',
    'Matosinhos e Leça da Palmeira',
    'Perafita, Lavra e Santa Cruz do Bispo',
    'São Mamede de Infesta e Senhora da Hora',
  ],
  'Paços de Ferreira': [
    'Carvalhosa',
    'Eiriz',
    'Ferreira',
    'Figueiró',
    'Frazão Arreigada',
    'Freamunde',
    'Meixomil',
    'Modelos',
    'Paços de Ferreira',
    'Penamaior',
    'Raimonda',
    'Sanfins Lamoso Codessos',
    'Seroa',
    'Sobreira',
    'Sobrosa',
    'Vandoma',
  ],
  'Paredes': [
    'Aguiar de Sousa',
    'Astromil',
    'Baltar',
    'Beire',
    'Besteiros',
    'Bitarães',
    'Castelões de Cepeda',
    'Cete',
    'Cristelo',
    'Duas Igrejas',
    'Gandra',
    'Gondalães',
    'Lordelo',
    'Louredo',
    'Madalena',
    'Mouriz',
    'Parada de Todeia',
    'Paredes',
    'Penafiel',
    'Penamaior',
    'Recezinhos (São Mamede)',
    'Recezinhos (São Martinho)',
    'Recarei',
    'Riobom',
    'Sobreira',
    'Sobrosa',
    'Sobreira',
    'Vandoma',
  ],
  'Penafiel': [
    'Abragão',
    'Aguieira',
    'Alpendorada, Várzea e Torrão',
    'Bustelo',
    'Cabeça Santa',
    'Canelas',
    'Capela',
    'Castelões',
    'Croca',
    'Duas Igrejas',
    'Eja',
    'Fonte Arcada',
    'Galegos',
    'Guilhufe e Urrô',
    'Irivo',
    'Lagares e Figueira',
    'Luzim e Vila Cova',
    'Milhundos',
    'Novelas',
    'Oldrões',
    'Paço de Sousa',
    'Perozelo',
    'Pigeiros',
    'Pinheiro',
    'Portela',
    'Rio de Moinhos',
    'Rio Mau e Arcos',
    'Santa Marta',
    'Santiago de Subarrifana',
    'São Mamede de Recezinhos',
    'Sebolido',
    'Valpedre',
    'Vila Cova',
  ],
  'Porto': [
    'Aldoar, Foz do Douro e Nevogilde',
    'Bonfim',
    'Campanhã',
    'Cedofeita, Santo Ildefonso, Sé, Miragaia, São Nicolau e Vitória',
    'Lordelo do Ouro e Massarelos',
    'Paranhos',
    'Ramalde',
  ],
  'Póvoa de Varzim': [
    'Aguçadoura e Navais',
    'Aver-o-Mar, Amorim e Terroso',
    'Balazar',
    'Beiriz',
    'Estela',
    'Laundos',
    'Póvoa de Varzim, Beiriz e Argivai',
    'Rates',
    'Rio Mau e Arcos',
    'Terroso',
    'Vila do Conde',
  ],
  'Santo Tirso': [
    'Agrela',
    'Água Longa',
    'Areias, Sequeiró, Lama e Palmeira',
    'Aves',
    'Campo (São Martinho)',
    'Carreira e Refojos de Riba de Ave',
    'Couto (Santa Cristina e São Miguel) e Burgães',
    'Guimarei',
    'Lamelas e Guimarei',
    'Monte Córdova',
    'Negrelos (São Mamede)',
    'Negrelos (São Tomé)',
    'Rebordões',
    'Reguenga',
    'Roriz',
    'Santo Tirso, Couto (Santa Cristina e São Miguel) e Burgães',
    'São Tomé de Negrelos',
    'Vilarinho',
  ],
  'Trofa': [
    'Alvarelhos e Guidões',
    'Bougado (São Martinho e Santiago)',
    'Covelas',
    'Muro',
    'São Mamede do Coronado',
    'São Romão do Coronado',
    'São Martinho de Bougado',
  ],
  'Valongo': [
    'Alfena',
    'Campo e Sobrado',
    'Ermesinde',
    'Valongo',
  ],
  'Vila do Conde': [
    'Árvore',
    'Aveleda',
    'Azurara',
    'Bagunte, Ferreiró, Outeiro Maior',
    'Fajozes',
    'Fornelo e Vairão',
    'Gião',
    'Guilhabreu',
    'Junqueira',
    'Labruge',
    'Macieira da Maia',
    'Malta e Canidelo',
    'Mindelo',
    'Modivas',
    'Retorta e Tougues',
    'Rio Mau e Arcos',
    'Touguinha e Touguinhó',
    'Vila Chã',
    'Vila do Conde',
    'Vilar e Mosteiró',
  ],
  'Vila Nova de Gaia': [
    'Arcozelo',
    'Avintes',
    'Canelas',
    'Canidelo',
    'Grijó e Sermonde',
    'Gulpilhares e Valadares',
    'Madalena',
    'Mafamude e Vilar do Paraíso',
    'Oliveira do Douro',
    'Pedroso e Seixezelo',
    'Sandim, Olival, Lever e Crestuma',
    'Santa Marinha e São Pedro da Afurada',
    'São Félix da Marinha',
    'Serzedo e Perosinho',
    'Vilar de Andorinho',
  ],
  'Abrantes': [
    'Abrantes (São Vicente e São João) e Alferrarede',
    'Aldeia do Mato e Souto',
    'Alvega e Concavada',
    'Bemposta',
    'Carvalhal',
    'Fontes',
    'Martinchel',
    'Mouriscas',
    'Pego',
    'Rio de Moinhos',
    'São Facundo e Vale das Mós',
    'Tramagal',
  ],
  'Alcanena': [
    'Alcanena e Vila Moreira',
    'Bugalhos',
    'Malhou, Louriceira e Espinheiro',
    'Minde',
    'Moitas Venda',
    'Serra de Santo António',
    'Vila Verde dos Francos',
  ],
  'Almeirim': [
    'Almeirim',
    'Benfica do Ribatejo',
    'Fazendas de Almeirim',
    'Raposa',
  ],
  'Alpiarça': [
    'Alpiarça',
  ],
  'Benavente': ['Barrosa', 'Benavente', 'Samora Correia', 'Santo Estêvão'],
  'Cartaxo': [
    'Cartaxo e Vale da Pinta',
    'Ereira e Lapa',
    'Pontével',
    'Valada',
    'Vale da Pedra',
  ],
  'Chamusca': [
    'Chamusca e Pinheiro Grande',
    'Parreira e Chouto',
    'Ulme',
    'Vale de Cavalos',
  ],
  'Constância': [
    'Constância',
    'Montalvo',
    'Santa Margarida da Coutada',
  ],
  'Coruche': [
    'Biscainho',
    'Coruche, Fajarda e Erra',
    'Couço',
    'Santana do Mato',
  ],
  'Entroncamento': [
    'Nossa Senhora de Fátima',
    'São João Baptista',
  ],
  'Ferreira do Zêzere': [
    'Águas Belas',
    'Areias e Pias',
    'Beco',
    'Chãos',
    'Ferreira do Zêzere',
    'Igreja Nova do Sobral',
    'Nossa Senhora do Pranto',
    'Nossa Senhora da Graça de Póvoa e Meadas',
    'Paio Mendes',
    'Santarém (Marvila), Santa Iria da Ribeira de Santarém, Santarém (São Salvador) e Santarém (São Nicolau)',
    'São Miguel do Rio Torto e Rossio ao Sul do Tejo',
  ],
  'Golegã': [
    'Azinhaga',
    'Golegã',
  ],
  'Mação': [
    'Amêndoa',
    'Cardigos',
    'Carvoeiro',
    'Envendos',
    'Ortiga',
    'São João do Peso',
    'Sardoal',
  ],
  'Ourém': [
    'Alburitel',
    'Atouguia',
    'Caxarias',
    'Espite',
    'Fátima',
    'Freixianda, Ribeira do Fárrio e Formigais',
    'Gondemaria e Olival',
    'Matas e Cercal',
    'Nossa Senhora da Piedade',
    'Nossa Senhora das Misericórdias',
    'Seiça',
    'Urqueira',
  ],
  'Rio Maior': [
    'Alcobertas',
    'Arrouquelas',
    'Arruda dos Pisões',
    'Asseiceira',
    'Azambujeira e Malaqueijo',
    'Fráguas',
    'Marmeleira e Assentiz',
    'Outeiro da Cortiçada e Arruda dos Pisões',
    'Rio Maior',
    'São João da Ribeira e Ribeira de São João',
  ],
  'Salvaterra de Magos': [
    'Glória do Ribatejo e Granho',
    'Marinhais',
    'Muge',
    'Salvaterra de Magos e Foros de Salvaterra',
  ],
  'Santarém': [
    'Abitureiras',
    'Abrã',
    'Achete, Azoia de Baixo e Póvoa de Santarém',
    'Alcanede',
    'Alcanhões',
    'Almoster',
    'Amiais de Baixo',
    'Arneiro das Milhariças',
    'Azoia de Cima e Tremês',
    'Casével e Vaqueiros',
    'Gançaria',
    'Moçarria',
    'Pernes',
    'Póvoa da Isenta',
    'Póvoa de Santarém',
    'Santarém (Marvila), Santa Iria da Ribeira de Santarém, Santarém (São Salvador) e Santarém (São Nicolau)',
    'São Vicente do Paul e Vale de Figueira',
    'Vale de Santarém',
  ],
  'Sardoal': [
    'Alcaravela',
    'Santiago de Montalegre e Beselga',
    'Valhascos',
  ],
  'Tomar': [
    'Além da Ribeira e Pedreira',
    'Alviobeira',
    'Asseiceira',
    'Beselga',
    'Carregueiros',
    'Casais e Alviobeira',
    'Madalena e Beselga',
    'Olalhas',
    'Paialvo',
    'Sabacheira',
    'São Pedro de Tomar',
    'Serra e Junceira',
    'Tomar (São João Baptista) e Santa Maria dos Olivais',
  ],
  'Torres Novas': [
    'Alcorochel',
    'Assentiz',
    'Brogueira, Parceiros de Igreja e Alcorochel',
    'Chancelaria',
    'Lapas',
    'Meia Via',
    'Olaia e Paço',
    'Pedrógão',
    'Riachos',
    'Ribeira Branca',
    'Santa Maria, Salvador e Santiago',
    'São Pedro',
    'Zibreira',
  ],
  'Vila Nova da Barquinha': [
    'Atalaia',
    'Moita do Norte',
    'Praia do Ribatejo',
    'Tancos',
    'Vila Nova da Barquinha',
  ],
  'Alcácer do Sal': [
    'Alcácer do Sal (Santa Maria do Castelo e Santiago) e Santa Susana',
    'Comporta',
    'São Martinho',
    'Torrão',
  ],
  'Alcochete': [
    'Alcochete',
    'Samouco',
    'São Francisco',
    'São João',
  ],
  'Almada': [
    'Almada, Cova da Piedade, Pragal e Cacilhas',
    'Caparica e Trafaria',
    'Charneca de Caparica e Sobreda',
    'Costa da Caparica',
    'Laranjeiro e Feijó',
    'Sobreda',
  ],
  'Barreiro': [
    'Alto do Seixalinho, Santo André e Verderena',
    'Barreiro e Lavradio',
    'Palhais e Coina',
    'Santo António da Charneca',
  ],
  'Grândola': [
    'Azinheira dos Barros e São Mamede do Sádão',
    'Carvalhal',
    'Grândola e Santa Margarida da Serra',
    'Melides',
  ],
  'Moita': [
    'Alhos Vedros',
    'Baixa da Banheira e Vale da Amoreira',
    'Gaio-Rosário e Sarilhos Pequenos',
    'Moita',
  ],
  'Montijo': [
    'Atalaia e Alto Estanqueiro-Jardia',
    'Canha',
    'Montijo e Afonsoeiro',
    'Pegões',
    'Sarilhos Grandes',
  ],
  'Palmela': [
    'Palmela',
    'Pinhal Novo',
    'Poceirão e Marateca',
    'Quinta do Anjo',
    'Vale de Barris',
  ],
  'Santiago do Cacém': [
    'Abela',
    'Alvalade',
    'Cercal',
    'Ermidas-Sado',
    'Santiago do Cacém, Santa Cruz e São Bartolomeu da Serra',
    'Santo André',
    'São Domingos e Vale de Água',
    'Vila Nova de Santo André',
  ],
  'Seixal': [
    'Aldeia de Paio Pires',
    'Amora',
    'Arrentela',
    'Corroios',
    'Fernão Ferro',
    'Seixal, Arrentela e Aldeia de Paio Pires',
  ],
  'Sesimbra': [
    'Castelo (Sesimbra)',
    'Quinta do Conde',
    'Santiago (Sesimbra)',
    'Sesimbra (Castelo)',
    'Sesimbra (Santiago)',
    'Sesimbra (São Cristóvão)',
    'Sesimbra (São Francisco Xavier)',
  ],
  'Setúbal': [
    'Gâmbia-Pontes-Alto da Guerra',
    'Sado',
    'Setúbal (São Julião, Nossa Senhora da Anunciada e Santa Maria da Graça)',
  ],
  'Sines': [
    'Porto Covo',
    'Sines',
  ],
  'Arcos de Valdevez': [
    'Aboim das Choças',
    'Aguiã',
    'Ázere',
    'Cabana Maior',
    'Cabreiro',
    'Cendufe',
    'Couto',
    'Eiras e Mei',
    'Gavieira',
    'Gondoriz',
    'Grade e Carralcova',
    'Guilhadeses e Santar',
    'Jolda (Madalena) e Rio Cabrão',
    'Jolda (São Paio)',
    'Miranda',
    'Monte Redondo',
    'Oliveira',
    'Paçô',
    'Padroso',
    'Prozelo',
    'Rio de Moinhos',
    'Rio Frio',
    'Sabadim',
    'São Jorge e Ermelo',
    'Senharei',
    'Sistelo',
    'Soajo',
    'Souto e Tabaçô',
    'Távora (Santa Maria e São Vicente)',
    'Vale',
    'Vilela, São Cosme e São Damião e Sá',
  ],
  'Caminha': [
    'Âncora',
    'Argela',
    'Arga (Baixo, Cima e São João)',
    'Arga de Baixo (São João e Souto)',
    'Arga de Cima',
    'Caminha (Matriz) e Vilarelho',
    'Dem',
    'Gondar e Orbacém',
    'Lanhelas',
    'Moledo e Cristelo',
    'Seixas',
    'Venade e Azevedo',
    'Vilar de Mouros',
  ],
  'Melgaço': [
    'Alvaredo',
    'Castro Laboreiro e Lamas de Mouro',
    'Chaviães e Paços',
    'Cristoval',
    'Fiães',
    'Gave',
    'Paderne',
    'Parada do Monte e Cubalhão',
    'Penso e Vila Chã',
    'Prado e Remoães',
    'São Gregório',
    'Vila',
  ],
  'Monção': [
    'Anhões e Luzio',
    'Barbeita',
    'Barroças e Taias',
    'Belver',
    'Cambeses',
    'Ceivães e Badim',
    'Lara',
    'Longos Vales',
    'Lordelo',
    'Mazedo e Cortes',
    'Merufe',
    'Messegães, Valadares e Sá',
    'Monção e Troviscoso',
    'Moreira',
    'Pias',
    'Pinheiros',
    'Podame',
    'Portela',
    'Riba de Mouro',
    'Sago, Lordelo e Parada',
    'Segude',
    'Tangil',
    'Trute',
  ],
  'Paredes de Coura': [
    'Agualonga',
    'Bico e Cristelo',
    'Castanheira',
    'Cossourado e Linhares',
    'Coura',
    'Cunha',
    'Infesta',
    'Mozelos',
    'Padornelo',
    'Parada',
    'Paredes de Coura e Resende',
    'Porreiras',
    'Rubães',
    'Vascões',
  ],
  'Ponte da Barca': [
    'Azias',
    'Boivães',
    'Bravães',
    'Britelo, Gémeos e Ourilhe',
    'Crasto, Ruivos e Grovelas',
    'Cuide de Vila Verde',
    'Lavradas',
    'Lindoso',
    'Nogueira',
    'Oleiros',
    'Ponte da Barca, Vila Nova de Muía e Paço Vedro de Magalhães',
    'Sampriz',
    'São João Baptista e Santiago',
    'São Lourenço',
    'Vade (São Pedro)',
    'Vade (São Tomé)',
    'Vila Chã (Santiago e Santa Leocádia)',
  ],
  'Ponte de Lima': [
    'Anais',
    'Arca e Ponte de Lima',
    'Ardegão, Freixo e Mato',
    'Beiral do Lima',
    'Bertiandos',
    'Boalhosa',
    'Bouça',
    'Brandara',
    'Cabaços e Fojo Lobal',
    'Cabração e Moreira do Lima',
    'Calheiros',
    'Calvelo',
    'Correlhã',
    'Estorãos',
    'Facha',
    'Feitosa',
    'Fontão',
    'Fornelos e Queijada',
    'Friastelas',
    'Gaifar',
    'Gandra',
    'Gemieira',
    'Gondufe',
    'Labruja',
    'Labrujó, Rendufe e Vilar do Monte',
    'Lanheses',
    'Lima (Santa Maria, Santa Leocádia e Moreira) e Deão',
    'Navió e Vitorino dos Piães',
    'Poiares',
    'Ponte de Lima (Santa Cruz), Vila Nova de Muía e Paço de Arcos',
    'Rebordões (Santa Maria)',
    'Rebordões (Souto)',
    'Refóios do Lima',
    'Ribeira',
    'Sá',
    'Sandiães',
    'Santa Comba',
    'Santa Cruz do Lima',
    'Seara',
    'Serdedelo',
    'Vilar do Monte',
  ],
  'Valença': [
    'Arão',
    'Boivão',
    'Cerdal',
    'Fontoura',
    'Friestas',
    'Ganfei',
    'Gondomil e Sanfins',
    'São Julião e Silva',
    'São Pedro da Torre',
    'Valença, Cristelo Covo e Arão',
    'Verdoejo',
  ],
  'Viana do Castelo': [
    'Afife',
    'Alvarães',
    'Amonde',
    'Anha',
    'Areosa',
    'Barroselas e Carvoeiro',
    'Cardielos e Serreleis',
    'Carreço',
    'Castelo do Neiva',
    'Chafé',
    'Darque',
    'Freixieiro de Soutelo',
    'Geraz do Lima (Santa Maria, Santa Leocádia e Moreira) e Deão',
    'Lanheses',
    'Mazarefes e Vila Fria',
    'Meadela',
    'Monserrate',
    'Montaria',
    'Nogueira, Meixedo e Vilar de Murteda',
    'Outeiro',
    'Perre',
    'Santa Marta de Portuzelo',
    'São Romão de Neiva',
    'Subportela, Deocriste e Portela Susã',
    'Torre e Vila Mou',
    'Vila Franca',
    'Vila de Punhe',
  ],
  'Vila Nova de Cerveira': [
    'Caminha (Matriz) e Vilarelho',
    'Candemil',
    'Cornes',
    'Covas',
    'Gondar',
    'Loivo',
    'Prado e Remoães',
    'Reboreda e Nogueira',
    'Sopo',
    'Vila Nova de Cerveira e Lovelhe',
    'Vila Nova de Cerveira e Lovelhe',
  ],
  'Alijó': [
    'Alijó',
    'Carlão e Amieiro',
    'Castedo e Cotas',
    'Favaios',
    'Pegarinhos',
    'Pinhão',
    'Pópulo e Ribalonga',
    'Sanfins do Douro',
    'Santa Eugénia',
    'São Mamede de Ribatua',
    'Vale de Mendiz, Casal de Loivos e Vilarinho de Cotas',
    'Vila Chã',
    'Vila Verde',
  ],
  'Boticas': [
    'Alturas do Barroso e Cerdedo',
    'Beça',
    'Boticas e Granja',
    'Codessoso, Curros e Fiães do Tâmega',
    'Covas do Barroso',
    'Dornelas',
    'Pinho',
    'Sapiãos',
    'Vilar e Viveiro',
  ],
  'Chaves': [
    'Águas Frias',
    'Anelhe',
    'Bustelo',
    'Calvão e Soutelinho da Raia',
    'Cela',
    'Cimo de Vila da Castanheira',
    'Curalha',
    'Eiras, São Julião de Montenegro e Cela',
    'Ervededo',
    'Faiões',
    'Lama de Arcos',
    'Loivos e Póvoa de Agrações',
    'Madalena e Samaiões',
    'Mairos',
    'Moreiras',
    'Nogueira da Montanha',
    'Oura',
    'Outeiro Seco',
    'Paradela e Granjinha',
    'Planalto de Monforte',
    'Redondelo',
    'Sanfins',
    'Santa Cruz/Trindade e Sanjurge',
    'Santa Leocádia',
    'Santa Maria Maior',
    'Santo António de Monforte',
    'Santo Estêvão',
    'São Pedro de Agostém',
    'Soutelo e Seara Velha',
    'Travancas e Roriz',
    'Tronco',
    'Vale de Anta',
    'Vidago (União das Freguesias de Vidago, Arcossó, Selhariz e Vilarinho das Paranheiras)',
    'Vidago, Arcossó, Selhariz e Vilarinho das Paranheiras',
    'Vila Verde da Raia',
    'Vilar de Nantes',
    'Vilarelho da Raia',
    'Vilela Seca',
  ],
  'Mesão Frio': [
    'Barqueiros',
    'Cidadelhe',
    'Fornelos',
    'Gestaçô',
    'Mesão Frio (Santo André)',
    'Oliveira',
    'Vila Jusã',
  ],
  'Mondim de Basto': [
    'Atei',
    'Bilhó',
    'Campanhó e Paradança',
    'Ermelo e Pardelhas',
    'Mondim de Basto',
    'Vilar de Ferreiros',
  ],
  'Montalegre': [
    'Cabril',
    'Cervos',
    'Chã',
    'Covelães',
    'Covelo do Gerês',
    'Ferral',
    'Fervidelas',
    'Meixedo e Padornelos',
    'Meixide',
    'Montalegre e Padroso',
    'Morgade',
    'Negrões',
    'Outeiro',
    'Pitões das Júnias',
    'Reigoso',
    'Salto',
    'Santo André',
    'Sarraquinhos',
    'Sezelhe e Covelães',
    'Solveira',
    'Tourém',
    'Venda Nova e Pondras',
    'Vilar de Perdizes e Meixide',
  ],
  'Murça': [
    'Candedo',
    'Carva e Vilares',
    'Fiolhoso',
    'Jou',
    'Murça',
    'Noura e Palheiros',
    'Valongo de Milhais'
  ],
  'Peso da Régua': [
    'Fontelas',
    'Galafura e Covelinhas',
    'Godim',
    'Loureiro',
    'Moura Morta e Vinhós',
    'Peso da Régua e Godim',
    'Poiares e Canelo',
    'Sedielos',
    'Vilarinho dos Freires',
  ],
  'Ribeira de Pena': [
    'Alvadia',
    'Canedo',
    'Cerva e Limões',
    'Ribeira de Pena (Salvador) e Santo Aleixo de Além-Tâmega',
    'Santa Marinha',
  ],
  'Sabrosa': [
    'Celeirós',
    'Covas do Douro',
    'Gouvães do Douro',
    'Parada de Pinhão',
    'Paços',
    'Provesende, Gouvães do Douro e São Cristóvão do Douro',
    'Sabrosa',
    'São Lourenço de Ribapinhão',
    'São Martinho de Anta e Paradela de Guiães',
    'Souto Maior',
    'Torre do Pinhão',
    'Vilarinho de São Romão',
  ],
  'Santa Marta de Penaguião': [
    'Alvações do Corgo',
    'Cumieira',
    'Fontes',
    'Lobrigos (São Miguel e São João Baptista) e Sanhoane',
    'Medrões',
    'Medrões',
    'Sever',
    'Vila Marim',
  ],
  'Valpaços': [
    'Água Revés e Crasto',
    'Algeriz',
    'Bouçoães',
    'Canaveses',
    'Ervededo e Boim',
    'Fornos do Pinhal',
    'Friões',
    'Padrela e Tazem',
    'Possacos',
    'Rio Torto',
    'Santa Maria de Emeres',
    'Santa Valha',
    'Santiago da Ribeira de Alhariz',
    'São João da Corveira',
    'Serapicos',
    'Sonim e Barreiros',
    'Tinhela e Alvarelhos',
    'Vales',
    'Valpaços e Sanfins',
    'Vassal',
    'Veiga de Lila',
    'Vilarandelo',
  ],
  'Vila Pouca de Aguiar': [
    'Alfarela de Jales',
    'Bornes de Aguiar',
    'Bragado',
    'Capeludos',
    'Sabroso de Aguiar',
    'Santa Marta da Montanha',
    'Soutelo de Aguiar',
    'Telões',
    'Tresminas',
    'Valoura',
    'Vila Pouca de Aguiar',
  ],
  'Vila Real': [
    'Adoufe e Vilarinho de Samardã',
    'Andrães',
    'Arroios',
    'Borbela e Lamas de Olo',
    'Campeã',
    'Constantim e Vale de Nogueiras',
    'Folhadela',
    'Guiães',
    'Justes',
    'Lamares, Selores e Botões',
    'Lordelo',
    'Mateus',
    'Mondrões',
    'Mouçós e Lamares',
    'Nogueira',
    'Parada de Cunhos',
    'Pena',
    'Quintã',
    'São Dinis',
    'São Pedro',
    'São Tomé do Castelo e Justes',
    'Torgueda',
    'Vale de Nogueiras e Meixedo',
    'Vila Cova',
  ],
  'Armamar': [
    'Aldeias',
    'Arícera e Goujoim',
    'Armamar',
    'Cimbres',
    'Folgosa',
    'Fontelo',
    'Queimada',
    'Queimadela',
    'Santa Cruz',
    'São Cosmado',
    'São Martinho das Chãs',
    'Vacalar',
  ],
  'Carregal do Sal': [
    'Beijós',
    'Cabanas de Viriato',
    'Currelos, Papízios e Sobral',
    'Oliveira do Conde',
    'Parada',
    'Santa Comba Dão',
    'São João de Areias',
    'São Joaninho',
    'Tonda',
    'Treixedo e Nagozela',
    'Vila Nova de Oliveirinha',
  ],
  'Castro Daire': [
    'Almofala de Baixo',
    'Alva',
    'Cabril',
    'Castro Daire',
    'Cujó',
    'Ermida e Figueiredo das Donas',
    'Gosende',
    'Gouviães e Urrô',
    'Mamouros, Alva e Ribolhos',
    'Mezio e Moura Morta',
    'Mões',
    'Moledo',
    'Monteiras',
    'Pepim',
    'Picão e Ermida',
    'Pinheiro',
    'Reriz e Gafanhão',
    'São Joaninho',
    'São Joaninho',
    'São Pedro do Sul, Várzea e Baiões',
    'São Vicente de Lafões',
    'Souselo',
  ],
  'Cinfães': [
    'Alhões, Bustelo, Gralheira e Ramires',
    'Cinfães',
    'Espadanedo',
    'Ferreiros de Tendais',
    'Fornelos',
    'Moimenta',
    'Nespereira',
    'Oliveira do Douro',
    'Santiago de Piães',
    'São Cristóvão de Nogueira',
    'Souselo',
    'Tarouquela',
    'Tendais',
    'Travanca',
  ],
  'Lamego': [
    'Avões',
    'Bigorne, Magueija e Pretarouca',
    'Britiande',
    'Cambres',
    'Cepões, Meijinhos e Melcões',
    'Cepões, Meijinhos e Melcões',
    'Ferreirim',
    'Ferreirim e Macieira',
    'Ferreiros de Avões'
  ],
  'Mangualde': [
    'Abrunhosa-a-Velha',
    'Alcafache',
    'Almeidinha',
    'Cunha Alta',
    'Cunha Baixa',
    'Espinho',
    'Fornos de Maceira Dão',
    'Freixiosa',
    'Mangualde, Mesquitela e Cunha Alta',
    'Moimenta de Maceira Dão e Lobelhe do Mato',
    'Póvoa de Cervães',
    'Quintela de Azurara',
    'Santiago de Cassurrães e Póvoa de Cervães',
    'São João da Fresta',
    'Travanca de Tavares',
    'Várzea de Tavares',
  ],
  'Moimenta da Beira': [
    'Alvite',
    'Arcozelos',
    'Baldos',
    'Cabaços',
    'Caria',
    'Castelo',
    'Cepões, Meijinhos e Melcões',
    'Leomil',
    'Moimenta da Beira e Rua',
    'Paradinha e Nagosa',
    'Passô',
    'Pêra Velha, Aldeia de Nacomba e Ariz',
    'Peva e Segões',
    'Sever',
    'Vilar',
  ],
  'Mortágua': [
    'Cercosa',
    'Espinho',
    'Marmeleira',
    'Mortágua, Vale de Remígio, Cortegaça e Almaça',
    'Pala',
    'Sobral',
    'Trezói',
  ],
  'Nelas': [
    'Canas de Senhorim',
    'Carvalhal Redondo e Aguieira',
    'Lapa do Lobo',
    'Moreira',
    'Nelas',
    'Santar',
    'Senhorim',
    'Vilar Seco',
  ],
  'Oliveira de Frades': [
    'Arca e Varzielas',
    'Destriz e Reigoso',
    'Oliveira de Frades, Souto de Lafões e Sejães',
    'Pinheiro',
    'Ribeiradio',
    'São João da Serra',
    'São Vicente de Lafões',
    'São Vicente de Lafões',
    'Souto de Lafões',
  ],
  'Penalva do Castelo': [
    'Antas e Matela',
    'Castelo de Penalva',
    'Esmolfe',
    'Germil',
    'Ínsua',
    'Lusinde',
    'Pindo',
    'Real',
    'Sezures',
    'Trancozelos',
    'Vila Cova do Covelo/Mareco',
  ],
  'Penedono': [
    'Antas e Ourozinho',
    'Beselga',
    'Castainço',
    'Granja',
    'Penela da Beira',
    'Penedono e Granja',
    'Póvoa de Penela',
    'Souto',
    'Vila Cova à Coelheira',
  ],
  'Resende': [
    'Anreade e São Romão de Aregos',
    'Barrô e Cepões',
    'Felgueiras e Feirão',
    'Freigil e Miomães',
    'Ovadas e Panchorra',
    'Paus',
    'Resende',
    'São Cipriano e Vilarelho',
    'São João de Fontoura',
  ],
  'Santa Comba Dão': [
    'Cordovil e Mira',
    'Cumieira',
    'Nagozela e Embra',
    'Ovoa e Vimieiro',
    'Pinheiro de Ázere',
    'Santa Comba Dão e Couto do Mosteiro',
    'São Joaninho',
    'São João de Areias',
    'Treixedo e Nagozela',
    'Treixedo e Nagozela',
  ],
  'São João da Pesqueira': [
    'Castanheiro do Sul',
    'Ervedosa do Douro',
    'Nagozelo do Douro',
    'Paredes da Beira',
    'Riodades',
    'São João da Pesqueira e Várzea de Trevões',
    'Soutelo do Douro',
    'Trevões e Espinhosa',
    'Vale de Figueira',
    'Valongo dos Azeites',
    'Vilarouco e Pereiros',
  ],
  'São Pedro do Sul': [
    'Bordonhos',
    'Carvalhais e Candal',
    'Figueiredo de Alva',
    'Manhouce',
    'Pindelo dos Milagres',
    'Pinho',
    'Santa Cruz da Trapa e São Cristóvão de Lafões',
    'São Félix',
    'São Martinho das Moitas e Covas do Rio',
    'Serrazes',
    'Sul',
    'Valadares',
    'Várzea',
    'Vila Maior',
    'Vila Pouca',
    'Vilarinho',
  ],
  'Sátão': [
    'Águas Boas e Forles',
    'Avelal',
    'Ferreira de Aves',
    'Mioma',
    'Rio de Moinhos',
    'Romãs, Decermilo e Vila Longa',
    'São Miguel de Vila Boa',
    'Sátão',
    'Silvã de Cima',
    'Vila Nova de Souto d\'El-Rei',
  ],
  'Sernancelhe': [
    'Arnas',
    'Carregal',
    'Chosendo',
    'Cunha',
    'Faia',
    'Ferreirim',
    'Fonte Arcada e Escurquela',
    'Freixinho',
    'Granjal',
    'Lamosa',
    'Macieira',
    'Penso',
    'Quintela',
    'Sernancelhe e Sarzeda',
    'Vila da Ponte',
  ],
  'Tabuaço': [
    'Barcos',
    'Chavães',
    'Granja do Tedo',
    'Longa',
    'Paradela e Granjinha',
    'Pinheiros',
    'Sendim e Atei',
    'Tabuaço',
    'Távora e Pereiro',
    'Valença do Douro',
  ],
  'Tarouca': [
    'Dalvares',
    'Gouviães e Ucanha',
    'Granja Nova e Vila Chã da Beira',
    'Mondim da Beira',
    'Salzedas',
    'São João de Tarouca',
    'Tarouca e Dálvares',
    'Várzea da Serra',
  ],
  'Tondela': [
    'Barreiro de Besteiros e Tourigo',
    'Campo de Besteiros',
    'Canas de Santa Maria',
    'Caparrosa e Silvares',
    'Castelões',
    'Dardavaz',
    'Ferreirós do Dão',
    'Guardão',
    'Lajeosa do Dão',
    'Lobão da Beira',
    'Molelos',
    'Mosteirinho',
    'Mosteiro de Fráguas',
    'Nandufe',
    'Parada de Gonta',
    'Sabugosa',
    'Santiago de Besteiros',
    'São João do Monte e Mosteirinho',
    'São Miguel do Outeiro e Sabugosa',
    'Tonda',
    'Tondela e Nandufe',
    'Vilar de Besteiros e Mosteiro de Fráguas',
  ],
  'Vila Nova de Paiva': [
    'Alhais',
    'Fráguas',
    'Pendilhe',
    'Queiriga',
    'Touro',
    'Vila Cova à Coelheira',
    'Vila Nova de Paiva, Alhais e Fráguas',
  ],
  'Viseu': [
    'Abraveses',
    'Barreiros e Cepões',
    'Boa Aldeia, Farminhão e Torredeita',
    'Bodiosa',
    'Calde',
    'Campo',
    'Cavernães',
    'Cota',
    'Couto de Baixo e Couto de Cima',
    'Faíl e Vila Chã de Sá',
    'Fragosela',
    'Lordosa',
    'Mundão',
    'Orgens',
    'Povolide',
    'Ranhados',
    'Repeses e São Salvador',
    'Ribafeita',
    'Rio de Loba',
    'São Cipriano e Vil de Souto',
    'São João de Lourosa',
    'São José',
    'São Pedro de France',
    'São Pedro do Sul, Várzea e Baiões',
    'Silgueiros',
    'Viseu',
  ],
  'Vouzela': [
    'Alcofra',
    'Cambra e Carvalhal de Vermilhas',
    'Campia',
    'Fataunços e Figueiredo das Donas',
    'Fornelo do Monte',
    'Queirã',
    'São Miguel do Mato',
    'Ventosa',
    'Vouzela e Paços de Vilharigues',
  ],
  'Angra do Heroísmo': [
    'Altares',
    'Cinco Ribeiras',
    'Doze Ribeiras',
    'Feteira',
    'Porto Judeu',
    'Posto Santo',
    'Raminho',
    'Ribeirinha',
    'Santa Bárbara',
    'Santa Luzia',
    'São Bartolomeu de Regatos',
    'São Bento',
    'São Mateus da Calheta',
    'São Pedro',
    'Sé',
  ],
  'Calheta (Açores)': [
    'Calheta',
    'Norte Pequeno',
    'Ribeira Seca',
    'Santo Antão',
    'Topo (Nossa Senhora do Rosário)',
  ],
  'Corvo': [
    'Corvo',
  ],
  'Horta': [
    'Capelo',
    'Castelo Branco',
    'Cedros',
    'Feteira',
    'Flamengos',
    'Matriz (Horta)',
    'Pedro Miguel',
    'Praia do Almoxarife',
    'Praia do Norte',
    'Ribeirinha',
    'Salão',
    'São Mateus',
    'Varadouro',
  ],
  'Lagoa (Açores)': [
    'Água de Pau',
    'Cabouco',
    'Lagoa (Nossa Senhora do Rosário)',
    'Ribeira Chã',
    'Santa Cruz',
  ],
  'Lajes das Flores': [
    'Fajã Grande',
    'Fajãzinha',
    'Lajes das Flores',
    'Lajedo',
    'Lomba',
    'Mosteiro',
    'Nossa Senhora do Rosário',
    'Santa Cruz das Flores',
  ],
  'Lajes do Pico': [
    'Calheta de Nesquim',
    'Lajes do Pico',
    'Piedade',
    'Ribeiras',
  ],
  'Madalena': [
    'Candelária',
    'Criação Velha',
    'Madalena',
    'São Caetano',
  ],
  'Nordeste': [
    'Achada',
    'Achadinha',
    'Algarvia',
    'Lomba da Fazenda',
    'Nordeste (Nossa Senhora da Conceição)',
    'Nordeste (São Pedro)',
    'Salga',
    'Santana',
    'Santo António de Nordestinho',
    'São Pedro de Nordestinho',
  ],
  'Ponta Delgada': [
    'Ajuda da Bretanha',
    'Arrifes',
    'Candelária',
    'Capelas',
    'Covoada',
    'Fajã de Baixo',
    'Fajã de Cima',
    'Fenais da Luz',
    'Feteiras',
    'Ginetes',
    'Livramento',
    'Mosteiros',
    'Pilar da Bretanha',
    'Ponta Delgada (São José)',
    'Ponta Delgada (São Pedro)',
    'Relva',
    'Remédios',
    'Rosto de Cão (Livramento)',
    'Santa Bárbara',
    'Santa Clara',
    'Santo António',
    'São Roque',
    'São Sebastião',
    'São Vicente Ferreira',
  ],
  'Povoação': [
    'Água Retorta',
    'Faial da Terra',
    'Furnas',
    'Nossa Senhora dos Remédios',
    'Povoação',
    'Ribeira Quente',
  ],
  'Praia da Vitória': [
    'Agualva',
    'Biscoitos',
    'Cabo da Praia',
    'Fonte do Bastardo',
    'Fontinhas',
    'Lajes',
    'Porto Martins',
    'Praia da Vitória (Santa Cruz)',
    'Quatro Ribeiras',
    'Santa Cruz',
    'Vila Nova',
  ],
  'Ribeira Grande': [
    'Calhetas',
    'Fenais da Ajuda',
    'Lomba da Maia',
    'Lomba de São Pedro',
    'Maia',
    'Pico da Pedra',
    'Porto Formoso',
    'Rabo de Peixe',
    'Ribeira Seca',
    'Ribeirinha',
    'Santa Bárbara',
    'São Brás',
    'São Mateus da Calheta',
  ],
  'Santa Cruz da Graciosa': [
    'Guadalupe',
    'Luz',
    'Praia',
    'Santa Cruz da Graciosa',
    'São Mateus',
  ],
  'Santa Cruz das Flores': [
    'Caveira',
    'Cedros',
    'Lajedo',
    'Lomba',
    'Mosteiro',
    'Nossa Senhora dos Remédios',
    'Santa Cruz das Flores',
  ],
  'São Roque do Pico': [
    'Prainha',
    'Santa Luzia',
    'Santo Amaro',
    'São Roque do Pico',
  ],
  'Velas': [
    'Manadas',
    'Norte Grande',
    'Ribeira Seca',
    'Rosais',
    'Santo Amaro',
    'Urzelina',
    'Velas (São Jorge)',
  ],
  'Vila do Porto': [
    'Almagreira',
    'Santa Bárbara',
    'Santo Espírito',
    'São Pedro',
    'Vila do Porto',
  ],
  'Vila Franca do Campo': [
    'Água de Alto',
    'Ponta Garça',
    'Ribeira das Tainhas',
    'Ribeira Seca',
    'São Miguel (Vila Franca do Campo)',
    'Vila Franca do Campo (São Miguel)',
  ],
  'Calheta': [
    'Arco da Calheta',
    'Calheta',
    'Estreito da Calheta',
    'Fajã da Ovelha',
    'Jardim do Mar',
    'Paul do Mar',
    'Ponta do Pargo',
    'Prazeres',
  ],
  'Câmara de Lobos': [
    'Câmara de Lobos',
    'Curral das Freiras',
    'Estreito de Câmara de Lobos',
    'Jardim da Serra',
  ],
  'Funchal': [
    'Imaculado Coração de Maria',
    'Monte',
    'Santa Luzia',
    'Santa Maria Maior',
    'Santa Maria Maior',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'São Martinho',
    'São Pedro',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque',
    'São Roque',
    'Santo António',
    'Santo António',
    'São Gonçalo',
    'São Martinho',
    'São Pedro',
    'São Roque'
  ],
  'Machico': [
    'Água de Pena',
    'Caniçal',
    'Machico',
    'Porto da Cruz',
    'Santo António da Serra',
  ],
  'Ponta do Sol': [
    'Canhas',
    'Madalena do Mar',
    'Ponta do Sol',
  ],
  'Porto Moniz': [
    'Porto Moniz',
    'Ribeira da Janela',
  ],
  'Porto Santo': [
    'Porto Santo',
  ],
  'Ribeira Brava': [
    'Campanário',
    'Ribeira Brava',
    'Serra de Água',
  ],
  'Santa Cruz': [
    'Camacha',
    'Caniço',
    'Gaula',
    'Santa Cruz',
    'Santo António da Serra',
  ],
  'Santana': [
    'Arco de São Jorge',
    'Faial',
    'Ilha',
    'Santana',
    'São Jorge',
  ],
  'São Vicente': [
    'Boaventura',
    'Ponta Delgada',
    'São Vicente',
  ]
};
