INSERT INTO EntidadeResponsavel (nome, codigo, descricao, pais) VALUES
('Centro de Saúde de Aveiro', 1000, 'Descrição do Centro de Saúde de Aveiro', 'Portugal'),
('Centro de Saúde de Beja', 2000, 'Descrição do Centro de Saúde de Beja', 'Portugal'),
('Centro de Saúde de Braga', 3000, 'Descrição do Centro de Saúde de Braga', 'Portugal'),
('Centro de Saúde de Bragança', 4000, 'Descrição do Centro de Saúde de Bragança', 'Portugal'),
('Centro de Saúde de Castelo Branco', 5000, 'Descrição do Centro de Saúde de Castelo Branco', 'Portugal'),
('Centro de Saúde de Coimbra', 6000, 'Descrição do Centro de Saúde de Coimbra', 'Portugal'),
('Centro de Saúde de Évora', 7000, 'Descrição do Centro de Saúde de Évora', 'Portugal'),
('Centro de Saúde de Faro', 8000, 'Descrição do Centro de Saúde de Faro', 'Portugal'),
('Centro de Saúde da Guarda', 9000, 'Descrição do Centro de Saúde da Guarda', 'Portugal'),
('Centro de Saúde de Leiria', 10000, 'Descrição do Centro de Saúde de Leiria', 'Portugal'),
('Centro de Saúde de Lisboa', 11000, 'Descrição do Centro de Saúde de Lisboa', 'Portugal'),
('Centro de Saúde de Portalegre', 12000, 'Descrição do Centro de Saúde de Portalegre', 'Portugal'),
('Centro de Saúde do Porto', 13000, 'Descrição do Centro de Saúde do Porto', 'Portugal'),
('Centro de Saúde de Santarém', 14000, 'Descrição do Centro de Saúde de Santarém', 'Portugal'),
('Centro de Saúde de Setúbal', 15000, 'Descrição do Centro de Saúde de Setúbal', 'Portugal'),
('Centro de Saúde de Viana do Castelo', 16000, 'Descrição do Centro de Saúde de Viana do Castelo', 'Portugal'),
('Centro de Saúde de Vila Real', 17000, 'Descrição do Centro de Saúde de Vila Real', 'Portugal'),
('Centro de Saúde de Viseu', 18000, 'Descrição do Centro de Saúde de Viseu', 'Portugal'),
('Centro de Saúde de Angra do Heroísmo', 19000, 'Descrição do Centro de Saúde de Angra do Heroísmo', 'Portugal'),
('Centro de Saúde do Funchal', 20000, 'Descrição do Centro de Saúde do Funchal', 'Portugal'),
('Centro de Saúde da Horta', 21000, 'Descrição do Centro de Saúde da Horta', 'Portugal'),
('Centro de Saúde de Lamego', 22000, 'Descrição do Centro de Saúde de Lamego', 'Portugal'),
('Centro de Saúde de Ponta Delgada', 23000, 'Descrição do Centro de Saúde de Ponta Delgada', 'Portugal');

DELETE FROM EntidadeResponsavel