INSERT INTO Especialidade (especialidade) VALUES 
('Alergologia'),
('Anestesiologia'),
('Angiologia'),
('Cardiologia'),
('Cirurgia Cardiovascular'),
('Cirurgia Geral'),
('Cirurgia Pediátrica'),
('Cirurgia Plástica'),
('Cirurgia Torácica'),
('Cirurgia Vascular'),
('Clínica Médica'),
('Dermatologia'),
('Endocrinologia'),
('Gastroenterologia'),
('Genética Médica'),
('Geriatra'),
('Ginecologia e Obstetrícia'),
('Hematologia'),
('Homeopatia'),
('Infectologia'),
('Mastologia'),
('Medicina de Emergência'),
('Medicina do Trabalho'),
('Medicina Esportiva'),
('Medicina Física e Reabilitação'),
('Medicina Intensiva'),
('Medicina Legal e Perícia Médica'),
('Medicina Nuclear'),
('Medicina Preventiva e Social'),
('Nefrologia'),
('Neurocirurgia'),
('Neurologia'),
('Nutrologia'),
('Oftalmologia'),
('Oncologia Clínica'),
('Ortopedia'),
('Otorrinolaringologia'),
('Patologia'),
('Pediatria'),
('Pneumologia'),
('Psiquiatria'),
('Radiologia e Diagnóstico por Imagem'),
('Radioterapia'),
('Reumatologia'),
('Urologia');
